### ISSUE TITLE
x86-64 is not compatible with the goal of simplicity

### ISSUE THREAD

**Issue by ddevault** [kisslinux/repo#100]
No one knows for sure how big the x86-64 instruction set is. It takes hundreds of instructions and esoteric hacks to boot up to long mode. EFI exists. Supporting cross-compiling is important to ensure the simpler architectures of the future are accounted for; a port to RISC-V for example should be relatively easy.

**Comment by dylanaraps** [comment]
You're welcome to fork and provide KISS for RISC-V, ARM or whatever architecture you prefer. I have no interest in doing this and as stated on the website, KISS supports only x86_64.

**Comment by ddevault** [comment]
Is simplicity a vague idea for vanity or an actual goal you're committed to?

**Comment by konimex** [comment]
I think this is more of a "problem" with the package manager rather than the distro itself (the package manager doesn't support cross-compiling AFAIC) so you might want to open an issue/make a PR there instead.

**Comment by ddevault** [comment]
Well, I brought it up here for lack of a better option, because there's nowhere to comment on the goals of the project itself. If the package manager supported it, it would be in conflict with the goals of the system, so addressing the problem at the system level is more appropriate.

**Comment by dylanaraps** [comment]
> Is simplicity a vague idea for vanity or an actual goal you're committed to?

Let's not stoop to claims like this, it's petty.

As I've said above, KISS is *only* for x86_64 and you're welcome (*and within your rights*) to fork and provide KISS for whatever architecture you desire.

**Comment by dylanaraps** [comment]
I'll add:

Your definition of simplicity may not align with mine (*and that's fine*). I started KISS with the goal of creating a "simple" distribution for x86_64 (*the only piece of technology I own uses this architecture*).

Other architectures are "out-of-scope" for KISS, however it's open source and as I've said, you're welcome to fork and port KISS to the architecture of your choice.

I do this for free and my time is very limited. One of the other goals was for KISS to be maintainable in my allotted amount of free time. This explains my reasons for pinning KISS to a single architecture from day 1 and for why the officially provided repositories are so small.

If you disagree with these design decisions you have two choices, fork and port KISS or use another Linux distribution.
