### ISSUE TITLE
Dropping Python 2

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#102]
Very simple in our case:

- [ ] Firefox
    - I hope this happens in my lifetime. 
- [ ] qt5-webengine
    - Maybe someday.
- [x] NodeJS
    - ~~Should be possible in the next release!~~
    - ~~See: https://github.com/nodejs/node/issues/25789~~
    - Turns out it's possible now. https://github.com/kisslinux/repo/commit/84efd40d3c7a62cd4a01a6bf6c14f291d620b05f

**Comment by E5ten** [comment]
qt5-webengine too now
