### ISSUE TITLE
Dropping GTK+2

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#103]
Easy once again.

- [ ] Firefox.
    - https://bugzilla.mozilla.org/show_bug.cgi?id=1377445

**Comment by astier** [comment]
How about dropping firefox in favor of brave. This may also remove the python2 dependency.

**Comment by dylanaraps** [comment]
Chromium based browsers are very difficult to get running on a `musl` based system and frankly, I have even less trust in Brave Browser than I do in Firefox (*for obvious reasons*). You're very welcome to package Brave Browser and offer it as an option in `community` or your own repository. 

Even KISS' Firefox package is just the "default" and "officially supported" option.

**Comment by astier** [comment]
> I have even less trust in Brave Browser than I do in Firefox (for obvious reasons)

What are those reasons if you don't mind sharing them?

**Comment by dylanaraps** [comment]
Sure,

- No source tarballs are made available. https://github.com/brave/brave-browser/issues/2588
    - You're forced to pull from `git` and use `npm` to build the browser. 
    - There's no download first, build later process.
    - This blocks it from **ever** being included in KISS' official repositories.
- Can system libraries be used in place of vendored ones?
    - (*I understand that some may **have** to be kept vendored*).
- Can it even be built on a `musl` based system?

I also have a few privacy concerns:

- The browser phones home.
    - "Safe Browsing" goes through Brave's servers.
    - Auto updates cannot be disabled.
        - Maybe possible at compile-time(?).
    - Filter list updates, etc.
    - Can this all be disabled?
- Based on Chromium.
    - Chock-full of Google.
    - Phones home to Google.
    - Do their patches **fully** remove Google's tracking?
- Can uBlock Origin be installed in place of their built in Adblocker/Tracking protection?
    - The built in blockers aren't "complete" or as good as uBlock.
    - The built in blockers have contained whitelists for Facebook etc in the past.

How can a business whose sole(?) revenue stream being user tracking/advertising also claim to then protect my privacy on the web? Common sense alone here would dictate that I shouldn't use this browsers (*just as I shouldn't use Chromium or Chrome*). 

I hope this gets my point across. :+1:

**Comment by dylanaraps** [comment]
Note: I've purposely left out arguments related to "Browser [engine] mono-culture", their Crypto Currency scheme, their attitude towards security issues etc as I'd like to keep my arguments technical in nature.

Putting all of my concerns to the side, Brave has **no** source distribution method which would be acceptable for KISS' official repositories. It's a no go from the get go.

**Comment by illiliti** [comment]
What do you think about ungoogled-chromium? It has pretty good patches for removing google bullshit,but it lack of patches for musl compatibility. Therefore, we can use alpine patches for musl compatibility.

Sorry for bad english

**Comment by dylanaraps** [comment]
https://github.com/kisslinux/repo/commit/9c6676b190486c79385130f8b551415cf3ed87c3
