### ISSUE TITLE
[core: mandoc] Source is down

### ISSUE THREAD

**Issue by dithpri** [kisslinux/repo#104]
mandoc.bsd.lv is down (DNS doesn't resolve). This might be a temporary issue, but as long as the site is down, it's impossible to build mandoc.

**Comment by dylanaraps** [comment]
Fixed. https://github.com/kisslinux/repo/commit/7f66036baf4ea2f53860b84a592637290c6c2eea

This isn't an official mirror but the existing checksums match exactly with upstream so it's fine while the site is down.
