### ISSUE TITLE
[extra: llvm] build script doesn't respect $MAKEFLAGS job limit

### ISSUE THREAD

**Issue by dithpri** [kisslinux/repo#105]
The llvm build script executes `make -j "$(nproc || echo 2)"` which sets the number of jobs to the number of cores (or 2). This ignores and overrides any values present in MAKEFLAGS.

Solutions:
* don't set -j
* only set -j if MAKEFLAGS not present or empty

**Comment by dylanaraps** [comment]
Fixed.
