### ISSUE TITLE
Unable to build GTK+2

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/repo#106]
Hi,

I tried to rebuild GTK+2 (after the update of mesa), but I get the following error:

```
Couldn't find include 'Pango-1.0.gir' (search path: '['../gdk', '/usr/share', 'gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0']')
make[4]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:156: Gdk-2.0.gir] Error 1
make[4]: Leaving directory '/home/macquat/.cache/kiss/build-16468/gtk+2/gdk'
make[3]: *** [Makefile:1381: all-recursive] Error 1
make[3]: Leaving directory '/home/macquat/.cache/kiss/build-16468/gtk+2/gdk'
make[2]: *** [Makefile:1161: all] Error 2
make[2]: Leaving directory '/home/macquat/.cache/kiss/build-16468/gtk+2/gdk'
make[1]: *** [Makefile:733: all-recursive] Error 1
make[1]: Leaving directory '/home/macquat/.cache/kiss/build-16468/gtk+2'
make: *** [Makefile:625: all] Error 2
!> gtk+2 Build failed
```

The problem is the following compilation option in the build of pango:

`-Dgir=false \`

Do you also have this problem ?

**Comment by dylanaraps** [comment]
I can't reproduce this, gtk+2 builds fine. Have you also rebuilt `pango`?

**Comment by tristelune1** [comment]
I had to modifiy gdk-pixbuf and remove 

`-Dgir=false \`

from the build. It was to package zathura. Pango builds fine. So the problem is somewhere else on my system.

**Comment by dylanaraps** [comment]
What's the error from `gdk-pixbuf` or does it build fine regardless?

**Comment by tristelune1** [comment]
Ok, the problem came from the package `gobject-introspection`. In that package some `gir` files were created. I have removed it and now it builds fine. Thank you!
