### ISSUE TITLE
Firefox difficult to use

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/repo#107]
Hi, 

at the moment it's difficult to use firefox. When I load a page and then scroll, it scrolls, then stops or blocks. I have to click on the menu icon such that I can scroll again. Then it blocks again, I click again on the menu, then one more time the same. It doesn't crash. 

It happens after the update of mesa (it probably also updates firefox to 69.0.3). Even If I write a comment or an url, sometimes I have to wait until the text is written. It seems, if I click on a tab, there is no problem. 

I have rebuilt the packages mentioned in the "news" of the website. Do you experience something similar ? In the last month I had problem with firefox. Perhaps it's time for me to drop it....... 

There is no other browsers in the repo. I see two options:

- do you think firefox in testing is usable at the moment ?
- would you advice another browser ? I 'm thinking about packaging webkit2gtk.

**Comment by dylanaraps** [comment]
I have zero Firefox issues on my machine and I can't reproduce any of this. 

> do you think firefox in testing is usable at the moment ?

Yes. Please try it out. It runs even faster than 69.X.X for me.

**Comment by dylanaraps** [comment]
Also:

Do `firefox &>log`, run it for a bit, close it and then upload the contents of the file `log` somewhere so we can see exactly why this is happening.

**Comment by tristelune1** [comment]
So for now nothing was written in the log file. I got the following in my terminal:

```
$ JavaScript error: , line 0: AbortError: The operation was aborted.
Sandbox: seccomp sandbox violation: pid 26864, tid 26864, syscall 16, args 2 21523 140728742945728 0 1 140728742945984.

(/usr/lib/firefox/firefox:26864): Gtk-WARNING **: 08:22:23.608: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(firefox:26698): Gtk-WARNING **: 08:22:57.859: Error loading theme icon 'dialog-question' for stock: Icon 'dialog-question' not present in theme Adwaita

(firefox:26698): Gtk-WARNING **: 08:22:57.893: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

[1]+  Done                    firefox
```

Another thing I don't understand: after starting firefox wihtout using an old session, also I get only one tab, I have the following:

```
$ pidof firefox
27469 27421 27373 27324 27266
```

I don't understand why so much processes. I have also:

```
$ ps | grep firefox
27266 user   0:16 firefox
27324 user   0:16 {Web Content} /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 1 -prefMapSize 189103 -parentBuildID 20191016062538 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 27266 tab
27373 user   0:00 {WebExtensions} /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 6171 -prefMapSize 189103 -parentBuildID 20191016062538 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 27266 tab
27469 user   0:00 {Web Content} /usr/lib/firefox/firefox -contentproc -childID 4 -isForBrowser -prefsLen 6903 -prefMapSize 189103 -parentBuildID 20191016062538 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 27266 tab
27590 user   0:00 grep firefox
```

I don't know if it helps. I also get an impression, after spending some time on a web page, there is no problem anymore. Perhaps a problem with the cache.

**Comment by dylanaraps** [comment]
Firefox uses multiple processes by default and this can be disabled in the settings. That terminal output is "fine" as well. Hm, this didn't indicate what could be causing the "bugs" you're seeing.

Are you running KISS on hardware or a virtual machine?

**Comment by tristelune1** [comment]
On hardware. But as I needed a working computer, the installation is not well finished at the moment. For example the locales are not configured, the host file, time, or I have to start the network each time I boot. Perhaps something is missing. But one week ago it works without problems. I'm compiling the 70 version. 

I kill one of the process of firefox and it seems better. I have to investigate.

**Comment by dylanaraps** [comment]
> What was the first version of firefox you packaged ?

It was `68.0.1` if I recall correctly. You should be able to find the package by using `git` in the repository.

**Comment by tristelune1** [comment]
So I tried  something extreme: I reinstalled everything. It was a good opportunity to test the installation process and this time it was fast, excepted the compilation time of some packages. Almost everything was recompiled (I kept my home partition and the `.cache` directory wasn't empty). 

Same problem as before, a little bit better. But this time the fonts are Liberation, before I used DejaVu. I had a doubt: do I have graphic acceleration enabled ? It seems yes:

```
$ glxinfo | grep DRI
Device: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)  (0x5912)
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)
```

I have tried to delete the directory `.mozilla` but without improvement. 

Was your patch for dbus needed for 68.0.1 ? I assume no.

**Comment by dylanaraps** [comment]
I've pushed the full Firefox 70 release to the repositories. Try it out and let me know if things improve. :+1:

**Comment by tristelune1** [comment]
Unfortunately, no. Perhaps it's even worse. For example, to do a search now I have to load google and then I can search. So I discoverd it was a setting. But to solve this, I think it's a 2 minutes fix. On my browser it's 5-10 minutes. 

The facts are the following: I absolutely need a browser. Nowadays it's impossible to do without one. I tried to download "firefox-bin" but I was unable to start it. The problem is perhaps not with firefox. But I'm afraid it could take time to solve. 

What would you suggest for another browser ? I see two solutions:

- webkitgtk: but then I realised there is a lot of to package. 
- netsurf or dillo. But unfortunately, some websites won't display properly. Unfortunately I have to access some websites which could be a problem to those browsers.

**Comment by yetanothergeek** [comment]
As an experiment, maybe you could bootleg the one from Alpine, just to see if it makes any difference:

http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/firefox-esr-68.1.0-r0.apk

(The *.apk is really just a *.tar.gz so it should be easy enought to extract it.)

**Comment by dylanaraps** [comment]
**Note**: This won't work if their Firefox binary links to different (*or "missing"*) system libraries.

**Comment by tristelune1** [comment]
How can I show you my hardware with busybox ? I know `pciutils`, but I remember there was a conflict. Busybox don't show a lot of information. Then I'll give you all informations I have. Or perhaps I have to install something else.

**Comment by dylanaraps** [comment]
`cat /proc/cpuinfo`, `kiss list`, `cat /proc/meminfo`, `glxinfo` (*if you have it*). 

This is a good start. :+1:.

**Comment by tristelune1** [comment]
Here: [pastebin](http://pastebin.fr/58834)

Is it possible I forgot to compile something in kernel ? 

With this computer I used Void linux and Crux. I can't remember some problems with Void. With Crux, sometimes I had to close Firefox, because it didn't respond anymore. But otherwise it was not slow. 

Here a link on a support forum: [Firefox forum](http://pastebin.fr/58834). There is there some information at start of firefox. 

Finally, it happens I write an url but I can't see it, after a few letters firefox blocks. Those letters are written, but not displayed. If I hit "Enter", immediately the website loads. It remembers me some softwares which wait for some amounts of data before they are displayed.There reason is the software is not fast enough. 

The problem arise after the update of mesa. But not only mesa were updated.

**Comment by dylanaraps** [comment]
Everything looks fine there.

Can I see `about:support` inside Firefox?

**Comment by tristelune1** [comment]
How can I output it to a file ? At the moment I only found I can get a user.js file.

**Comment by tristelune1** [comment]
What a new world!!!!! :smiley: !!!!

I think the reason was here:

```
Decision Log
HW_COMPOSITING:
blocked by env: Acceleration blocked by platform
OPENGL_COMPOSITING:
unavailable by default: Hardware compositing is disabled
GPU_PROCESS:
unavailable by env: Hardware compositing is unavailable.
WEBRENDER:
opt-in by default: WebRender is an opt-in feature
WEBRENDER_QUALIFIED:
blocked-release-channel-intel by env: Release channel and Intel
```

I changed the following in `about:config`

```
layers.acceleration.disabled      modified    boolean false
layers.acceleration.force-enabled     modified boolean false
```

I set both of them on true. 

And now it's a real pleasure. I have never done that. I don't know at the moment really what it is, probably graphic acceleration. There are several options beginning with `layers.acceleration`. Could you tell me what you have there ? Do you know what is it ?

**Comment by tristelune1** [comment]
Ok, thank you, I will also try your last suggestion. I don't know if the problem had to do with the update of mesa (19.2.1). But after that update with other packages, I had to do some modifications, even to start Xorg. I don't know if it can be a problem for somebody else.  Thank you very much :+1: :+1: !!
