### ISSUE TITLE
freetype-harfbuzz: dependency missing ?

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/repo#108]
During a fresh install of kiss, I got the following error:

` fatal error: ft2build.h: No such file or directory`

If I remember right, it was during the installation of `libXfont2`. I had an error displayed after executing `freetype-config` which said libpng was missing. After installing `libpng`, I was able to install libXfont2. Probably `libpng` must be added as a dependency of `freetype-harfbuzz`. One week ago I didn't had this problem.

**Comment by dylanaraps** [comment]
Should be fixed in: https://github.com/kisslinux/repo/commit/6058f9a0c259699fa8e32386dc032056dc653b05

**Comment by dylanaraps** [comment]
Thanks!
