### ISSUE TITLE
Firefox can't use whereby video conversation (privacy settings related)

### ISSUE THREAD

**Issue by axpira** [kisslinux/repo#110]
I tried to use a whereby.com to do a conference and it's not possible.

It's showing a message: This browser doesn't support video conersations.

I tried this https://whereby.helpscoutdocs.com/article/345-im-using-firefox-but-whereby-says-my-browser-isnt-supported , but keep with the same message.

**Comment by dylanaraps** [comment]
The default KISS Firefox builds have `webrtc` disabled as it and `media.peerconnection.enabled = true` are a privacy concern. You will need to build Firefox with these enabled for the feature you desire to work.

- Remove `ac_add_options --disable-webrtc` from `files/mozconfig`.
- Remove `pref("media.peerconnection.enabled", false);` from `files/vendor.js`.
- Rebuild.

**Comment by axpira** [comment]
Thanks, I changed this and now is working.

So now when I try to share screen show a message: "The browse have trouble accessing your screen".

Do you known why?

**Comment by dylanaraps** [comment]
Rename `/usr/lib/firefox/browser/defaults/preferences/vendor.js` to something else (`vendor.js.bak`) and see if it works. :+1:

**Comment by dylanaraps** [comment]
Ping @axpira
