### ISSUE TITLE
rust build failed due to libressl version out of range

### ISSUE THREAD

**Issue by jsvlrt** [kisslinux/repo#111]
if you look at https://github.com/kisslinux/repo/blob/master/extra/rust/patches/musl-libressl.patch#L175 version 3.0.0 is supported however version 3.0.2 is the latest version of libressl that i have built...

this should be a simple fix no?

**Comment by dylanaraps** [comment]
Testing a build now. Thanks for reporting. :+1:

**Comment by dylanaraps** [comment]
Upstream bug report: https://github.com/rust-lang/rust/issues/65808

**Comment by dylanaraps** [comment]
Fixed in https://github.com/kisslinux/repo/commit/765ef16aa18b6c86889703da21d5240154026abf
