### ISSUE TITLE
Replacing Firefox with Seamonkey?

### ISSUE THREAD

**Issue by scsijon** [kisslinux/repo#112]
Since there seems some 'wants' around to replace firefox, not sure why, but I've not had problems so far, but if so, what about seamonkey, still built with the same engine and it has news, email and web development components in the standard build, so saving extra application space, and with a decent number of enhancements available also.

http://www.seamonkey-project.org/ is the url.

**Comment by dylanaraps** [comment]
Firefox will be the only browser in the official repositories. :+1:
