### ISSUE TITLE
Consider replacing Busybox with Toybox

### ISSUE THREAD

**Issue by scsijon** [kisslinux/repo#113]
Toybox is built and maintained from  this url > http://landley.net/toybox/index.html
Rob was involved with Busybox before moving on.
Toybox is simple, small, fast, and reasonably standards-compliant (POSIX-2008 and LSB 4.1).
This page http://landley.net/toybox/status.html gives you some idea of the varying commands status's for what's already in there. It's not always up to date though.
And he's willing to add others, both commands and switches to existing commands, that others want added as long as they are justifyable, just ask.

**Comment by dylanaraps** [comment]
I don't see a reason to replace `busybox` with `toybox` by default. Nothing stops you as a user from doing this yourself though. :+1:
