### ISSUE TITLE
grub fails to install 

### ISSUE THREAD

**Issue by stallonen** [kisslinux/repo#114]
When I try installing grub , I get the following error message 
`modprobe: can't change directory to '5.3.8-gentoo': No such file or directory`  
I am trying to install KISS linux by chroot'ing from my gentoo install .

**Comment by dylanaraps** [comment]
I'll need some more information. What `grub` commands are you running?

**Comment by stallonen** [comment]
I have ran this command 
`grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
`
my `df -h` output is as follows

`Filesystem                Size      Used Available Use% Mounted on`
`/dev/sdb4               108.9G      2.5G    100.8G   2% /`
`/dev/sdb2               126.0M     22.6M    103.4M  18% /boot`
`devtmpfs                 10.0M         0     10.0M   0% /dev`

**Comment by dylanaraps** [comment]
Output of `ls /boot`?

**Comment by stallonen** [comment]
output of `ls-boot'
`drwxr-xr-x    4 root     root           512 Nov  5 12:08 EFI`

`-rwxr-xr-x    1 root     root       3332380 Nov  5 12:15 System.map`

`-rwxr-xr-x    1 root     root       3332380 Nov  5 11:54 System.old`

`drwxr-xr-x    5 root     root           512 Nov  5 12:18 grub`

`-rwxr-xr-x    1 root     root       6562688 Nov  5 12:15 vmlinuz`

`-rwxr-xr-x    1 root     root       6562688 Nov  5 11:54 vmlinuz.old`

**Comment by dylanaraps** [comment]
Your kernel and system map need to be renamed, see: https://getkiss.org/pages/install#install-the-kernel

For some reason `grub` is finding your Gentoo kernel. Not sure why.

**Comment by stallonen** [comment]
Yep , I tried that , but it still didn't work .

**Comment by dylanaraps** [comment]
Can I see the full output from `grub`?

**Comment by stallonen** [comment]
here it is 
`drwxr-xr-x    2 root     root           512 Nov  5 12:02 fonts`
`-rwxr-xr-x    1 root     root          2156 Nov  5 13:08 grub.cfg`
`-rwxr-xr-x    1 root     root          1024 Nov  5 12:02 grubenv`
`drwxr-xr-x    2 root     root           512 Nov  5 12:02 locale`
`drwxr-xr-x    2 root     root         19968 Nov  5 13:19 x86_64-efi`

**Comment by dylanaraps** [comment]
I meant the `grub` commands used to install `grub`, where the error output occurs. Apologies.

**Comment by stallonen** [comment]
I am attempting a re-install now , to check if I badly messed up somewhere . If the issue persists , I will let you know , else I will close the issue !

**Comment by stallonen** [comment]
Yep , it was completely my fault , grub was installed properly , but I didn't install the bootup scripts , hence couldn't boot . 
But I still don't understand this error `modprobe: can't change directory to '5.3.8-gentoo': No such file or directory` . I don't think grub should be showing this . I am  closing the issue , but I would like some more information on this , preferably in a new issue ?

**Comment by dylanaraps** [comment]
I have no idea about that error. Grub by default shouldn't run `modprobe` from what I've seen.

**Comment by iainjreid** [comment]
In case any investigation went into this issue, I just had the same `modprobe` error. Does anybody have any clues? I'll keep going with the installation, and report back though! Loving the work @dylanaraps.

**Comment by lucat1** [comment]
I think the modprobe error could come from grub (for some reason) calling the `modprobe` tool which reads the `/lib/modules/<kernel release>` directory in search for kernel modules. I believe your current kernel release differs from the actual release you built kernel modules for. You can check if they match via the following commands:
```
uname -r # currently running kernel release
```

```
ls /lib/modules # list of available kernel modules releases
```

**Comment by depsterr** [comment]
> I have no idea about that error. Grub by default shouldn't run `modprobe` from what I've seen.

Checked the source and at line 111 of `grub-core/osdep/linux/platform.c` grub uses modprobe to load efivars.

```c
grub_util_exec_redirect_all((const char * []){ "modprobe", "efivars", NULL },
                NULL, NULL, "/dev/null");
```

**Comment by naurias** [comment]
I am having the same problem and baseinit installation didn't help either also my efivars isn't empty
