### ISSUE TITLE
rust sources

### ISSUE THREAD

**Issue by scsijon** [kisslinux/repo#119]
just a comment, wondering if it wouldn't be better to use github as the place for your rust sources?
there all at https://github.com/rust-lang
regards

also may be worth keeping a lookout at mrustc

**Comment by dylanaraps** [comment]
There's a difference between the release tarballs and git snapshots no? Either way, the official website is still an official release channel for the project.

I'm keeping an eye on `mrustc`. The only downside is that it lags around a year behind upstream (*I understand that it's a lot of work and I'm very thankful that it even exists!*). The intention is to provide the latest `rust` to users.

I'll definitely toy around with it as a means of possibly simplifying our bootstrap of rust. :)

**Comment by scsijon** [comment]
The only thing that worries me with rust is the cargo module, it downloads packages it needs to complete a rust build without intervention. i.e. as I understand it, you can't refuse to allow a particular package to be downloaded>built>installed.

**Comment by dylanaraps** [comment]
Our rust package downloads **everything** beforehand. The build works without a network connection and every source has checksums verified. Every package in the official repositories is like this. :+1
