### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#120]
- Drop packages.
    - [ ] `python2`
        - Waiting on Firefox.
    - [ ] `gtk+2`
        - Waiting on Firefox.
- [ ] Documentation.
    - [ ] Creating your own repository.
        - Document how to create your own repository and add it to `KISS_PATH`.
    - [ ] Forking packages.
        - Document how to "fork" a repository package to your own personal repository.
    - [ ] Package guidelines for `kisslinux/community` (extending the `README`).
        - One Pull Request per package.
        - Prefer `./configure` arguments broken one per line.
        - Preferred `cmake` syntax (See `libjpeg-turbo`).
        - Prefer simple `sed` commands over patches.
        - ...
    - [ ] Wiki guidelines.
        - Keep pages centered on "How to do X" instead of general software pages. Think of the Wiki pages as examples more so than manual pages. If that makes sense...
        - Correct spelling, grammar and punctuation.

**Comment by sdsddsd1** [comment]
I am interested in writing stuff but I would need some hints what each paragraph should contain

**Comment by dylanaraps** [comment]
I've added some further information for what I envision being written for each point. I hope it helps. :+1:
