### ISSUE TITLE
wpa_supplicant cannot connect using valid config

### ISSUE THREAD

**Issue by owm111** [kisslinux/repo#122]
wpa_supplicant will not connect to network using config generated with wpa_passphrase. This same config works on an Archlinux live USB's wpa_supplicant (both v2.9).

I am loading kernel modules from the live USB's `lsmod` and applying `awk '{ print "modprobe "$1 }'`. Firmware was added from `linux-firmware-20191022` (as listed in installation guide); `dmesg | grep firmware` yields no errors. The interface appears in both OS's `ip link` (as `wlan0` in KISS and `wlp59s0` in Arch).

Since the computer in question is my only computer and its internet isn't working, pictures of the screen are used instead of plaintxt (apologies).

Diff of modules loaded into Arch and modules loaded KISS:
![20191129_092406](https://user-images.githubusercontent.com/7798336/69878857-a4088f80-128b-11ea-8b53-426f8737e67b.jpg)

Comparison of `dmesg | grep ath10k`:
![20191129_092434_HDR](https://user-images.githubusercontent.com/7798336/69878949-d619f180-128b-11ea-8e7d-188fefb44986.jpg)

Comparison of wpa_supplicant output using same conifg:
![20191129_092749_HDR](https://user-images.githubusercontent.com/7798336/69879183-6d7f4480-128c-11ea-91d0-b763561e4717.jpg)

I tried to copy the wpa_supplicant bin from Arch to KISS, but `-sh: ./wpa_supplicant-arch: not found` (even though `ls -l` says it exists and is executable).

**Comment by dylanaraps** [comment]
It sounds to me like your kernel is missing some Wifi crypto options.

Do you have these enabled?:

```
CONFIG_IEEE80211_CRYPT_WEP=y
CONFIG_IEEE80211_CRYPT_CCMP=y
CONFIG_IEEE80211_CRYPT_TKIP=y
```

> I tried to copy the wpa_supplicant bin from Arch to KISS, but -sh: ./wpa_supplicant-arch: not found (even though ls -l says it exists and is executable).

This is due to Arch using `glibc` and KISS usng `musl`. :)

**Comment by owm111** [comment]
Worked perfectly! It appears I simply forgot to load them (built as modules, `lib80211_crypt_{ccmp,tkip,wep}`).
