### ISSUE TITLE
Firefox checksum  mismatch

### ISSUE THREAD

**Issue by arnolddinkla** [kisslinux/repo#128]
Firefox checksum issues when running kiss update. Terminal output below

!> firefox Failed to generate checksums
-> firefox Checksum mismatch
!> Checksum mismatch with: firefox

**Comment by dylanaraps** [comment]
The download may have failed to complete. Try `rm -f ~/.cache/kiss/sources/firefox/firefox-72.0b9.source.tar.xz` and then `kiss update` again. :+1:

**Comment by arnolddinkla** [comment]
Sorted. Thank you.
