### ISSUE TITLE
Binary packages 

### ISSUE THREAD

**Issue by LinArcX** [kisslinux/repo#129]
Hi. I very like your idea and your distro. But I think if users can install some software(for example Firefox, neovim , gimp) in binary fashion, it will be more better and time saving for them. What's your idea?

Edit: I remember that when I was working with Gentoo, it was too hard to compile huge softwares like Firefox. Is kiss same?

**Comment by dylanaraps** [comment]
Compiling anything is as simple as `kiss build pkg` (even Firefox). KISS is solely a source based distribution.

In fact, nothing stops any KISS user from providing binaries for Firefox (or any package) right now. The tarballs located in `~/.cache/kiss/bin` can be installed on any KISS machine (so long as `-march=native` wasn't used). The command is simply `kiss install /path/to/tarball`.

I have no current plans to provide official binaries for Firefox though I can't totally discard this for the future. Thanks for opening this issue. :)
