### ISSUE TITLE
Propose: Alternatives to eudev

### ISSUE THREAD

**Issue by illiliti** [kisslinux/repo#133]
What do you think about [mdevd](https://skarnet.org/software/mdevd/) or plain busybox mdev?

**Comment by dylanaraps** [comment]
This is something I want to explore. There is a fork of `libinput` which removes the `udev` dependency which allows Xorg to continue to function as normal.

I'll spend some time over the next few weeks testing this locally.

**Comment by dylanaraps** [comment]
Done. :)

https://github.com/kisslinux/wiki/wiki/Replacing-eudev-with-mdev-(or-another-device-manager)

My system (working with no device manager and working with `mdev`):

```
-> kiss l eudev
-> Package 'eudev' is not installed
```
