### ISSUE TITLE
git: support add --patch

### ISSUE THREAD

**Issue by jedahan** [kisslinux/repo#137]
`git add --patch` is really nice for interactive chunking of commits. Unfortunately, it requires perl, and we compile with `NO_PERL=YesPlease`. Would you be open to removing this option if git autodetects if perl is installed?

**Comment by dylanaraps** [comment]
Should be fixed in: https://github.com/kisslinux/repo/commit/7f6c33cfc1a377758cd56f8721f98026eed78ca7
