### ISSUE TITLE
e2fsprogs: /lib/pkgconfig/ext2fs.pc is missing

### ISSUE THREAD

**Issue by jelinekto** [kisslinux/repo#155]
This makes it impossible to build `btrfs-progs` (and possibly others).

**Comment by jelinekto** [comment]
Changing `make MKDIR_P="install -d" DESTDIR="$1" install install-libs` to `make MKDIR_P="install -d" DESTDIR="$1" install-progs-recursive` in the last commit is the culprit.

**Comment by dylanaraps** [comment]
Fixed. Rationale for the change which broke it is in the commit too. Thanks. :+1:
