### ISSUE TITLE
Usage link is broken in release section

### ISSUE THREAD

**Issue by Akeboshiwind** [kisslinux/repo#164]
The title says it all, but for more info:
It currently links to a presumably old repo and should be updated to either the script in the `kiss` repo or the install page on the website.

**Comment by dylanaraps** [comment]
Which page? Apologies for not understanding.

**Comment by Akeboshiwind** [comment]
Ah sorry, this is on the Releases tab in github itself.

**Comment by dylanaraps** [comment]
Fixed, thanks for opening all of these issues.

**Comment by Akeboshiwind** [comment]
No problem, thanks for appreciating them :)
