### ISSUE TITLE
busybox: checksum mismatch

### ISSUE THREAD

**Issue by IslandAlpha** [kisslinux/repo#166]
Offending file is mdev.run:

What I generated:
`f857fea99533df7b780c911bae19b0029a70ee1c8d36b49e7782604fb9cf25f8  mdev.run`

In busybox/checksums:
`138c4ac819cf65f4fc241570aa91cfe1d6b0d44359e91d4be88a902f0ca68d81  mdev.run`

**Comment by dylanaraps** [comment]
My bad.
