### ISSUE TITLE
Package request: ripgrep

### ISSUE THREAD

**Issue by Jackojc** [kisslinux/repo#17]
`ripgrep` is a rust written alternative to `grep`. It would supplement the capabilities of normal grep for a few cases. I specifically use it a lot for when browsing around a code repo.

**Comment by naltun** [comment]
`ripgrep` is a great tool. I use it nearly every day at work.

@Jackojc I'll go ahead and make a PR for ripgrep.

> When a package is added to public it is assumed that the first committer is now the maintainer of said package.
Sure, why not.

I can get to this tomorrow as today I'm moving. 🤷‍♂

**Comment by naltun** [comment]
I'm getting to this tonight. I finished moving last night.

**Comment by dylanaraps** [comment]
`rust` still needs to be fixed. On it.

**Comment by naltun** [comment]
I am currently working on this issue and have made progress [here](https://github.com/naltun/repo/commits/add-ripgrep).

Currently I have KISS installing in a VM (been going on for some hours), so in the mean time I am in a chroot environment.

I am waiting to generate a checksum (which will presumably work once KISS is _installed_ somewhere).
![image](https://user-images.githubusercontent.com/7507990/61604804-08964c80-ac11-11e9-820c-39f9a5596460.png)

Any feedback is welcome.

**Comment by naltun** [comment]
@Jackojc, behold #38 

@dylanaraps or @konimex, please review.

**Comment by Jackojc** [comment]
Awesome!

**Comment by naltun** [comment]
@Jackojc I fubar'd the commit history by having an Arch Linux maintainer's authorship in the commit history... Don't ask.

I'm redoing this today.

**Comment by naltun** [comment]
@Jackojc #39 is our friend ripgrep.

**Comment by dylanaraps** [comment]
Rust is now packaged, fire away.

**Comment by whoizit** [comment]
`cargo install ripgrep`
or
`cargo install repgrep_all`

**Comment by naltun** [comment]
@dylanaraps Perfect, I'll get this out this afternoon.

**Comment by naltun** [comment]
This is needed:
![image](https://user-images.githubusercontent.com/7507990/62624195-8be1be80-b8f0-11e9-822c-ba076190a2d8.png)

We see it specified here:
![image](https://user-images.githubusercontent.com/7507990/62624230-9f8d2500-b8f0-11e9-88e7-297d2b0a2d2b.png)

This patch is found, though:
![image](https://user-images.githubusercontent.com/7507990/62624305-cb100f80-b8f0-11e9-99ed-c5c904b71a53.png)

**Comment by konimex** [comment]
Pushed https://github.com/kisslinux/repo/commit/3b450931df5cd26611932c01168ac7d8f4143fe7. Please update the repo.

**Comment by naltun** [comment]
@konimex Doing so now.

**Comment by naltun** [comment]
![image](https://user-images.githubusercontent.com/7507990/62625268-d82dfe00-b8f2-11e9-9f8e-e3e84b507659.png)

@konimex What's the remediation for this?

**Comment by konimex** [comment]
Update busybox first then install `bzip2`. Our apologies since our `core` isn't really stable right now.

**Comment by naltun** [comment]
@konimex, no need to apologize. I'm happy to help sort out the kinks in the system. I'll do this later, after work.

**Comment by dylanaraps** [comment]
Re-open this in https://github.com/kisslinux/community
