### ISSUE TITLE
python: -fno-semantic-interposition is not possible with Clang

### ISSUE THREAD

**Issue by konimex** [kisslinux/repo#177]
## Description

Note: I don't know about your position in Clang as default compiler, but I know you do allow the option for people using Clang for every single package if set manually using `$CC`.

Clang's compiler doesn't support `-fno-semantic-interposition` as a valid {C{,XX},LD}FLAGS, so any commands thrown with this flag will error out.

Here's the log: https://termbin.com/cca0o

**Comment by dylanaraps** [comment]
I'll go ahead with my plan to make /usr/bin/python static which brings in better performance gains (though it's a pain in the ass to get working).
