### ISSUE TITLE
vim: build fails

### ISSUE THREAD

**Issue by mcpcpc** [kisslinux/repo#193]
On fresh KISS install, vim build fails.  This can be reproduced by following my build/install order: https://github.com/mcpcpc/kiss-sequoia-install

`kiss b vim`

```

-> Resolving dependencies 
-> Building: vim 
-> vim Checking repository files
-> Checking for pre-built dependencies 
-> vim Downloading sources
-> vim Cloning https://github.com/vim/vim
Cloning into '.'...
fatal: unable to find remote helper for 'https'
ERROR vim Failed to clone git+https://github.com/vim/vim

```

Additional note: vim is dependent on the `git` package but (i believe) is not listed in dependencies?    therefore, building without git already installed results in several additional errors.

**Comment by illiliti** [comment]
this issue caused by libressl update. you need to rebuild packages(in this case it's `curl`) which depend on libressl.
use this command to see which libraries/binaries required rebuild:
```sh
for i in /lib/* /bin/*; do ldd "$i"; done 2>&1 | grep -i 'error loading'
```
but really i think kiss should handle this automatically

**Comment by dylanaraps** [comment]
> fatal: unable to find remote helper for 'https'

As stated by @illiliti, you need to rebuild whatever linked to `libressl`. This should have happened
automatically during `kiss u` but of course, this automation is prone to errors like these. It's no big deal though.

> Additional note: vim is dependent on the git package but (i believe) is not listed in dependencies? therefore, building without git already installed results in several additional errors.

Git is a dependency of the package manager so it should be installed regardless. Also, repositories (with remotes) also require git anyway.

**Comment by mcpcpc** [comment]
Thanks! Works now.  First time encountering this issue after multiple fresh installs over the past few weeks...  would it be worth the inclusion/mention of this in the main KISS installation instructions?
