### ISSUE TITLE
Introducing switches for explicitly exluded software.

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/repo#195]
As I saw in the wiki you are planing to give wayland some room.
How do you feel about introducing wayland specific switches like it is done for webkit and gstreamer?
Gtk+3, mesa and firefox need wayland explicitly enabled. 
I have worked out modified buildfiles for [mesa](https://github.com/sdsddsd1/mywayland/blob/master/wayland/mesa/build) and [gtk+3](https://github.com/sdsddsd1/mywayland/blob/master/wayland/gtk%2B3/build).  
For firefox I had no luck yet, because `--disable-default-toolkit=cairo-gtk3-wayland` is not a valid option.

**Comment by dylanaraps** [comment]
I have no plans to support Wayland officially. My intention with the Wiki was to give the Community a place to document information about swapping to Wayland, running Wayland, etc. The home page is still a
