### ISSUE TITLE
Live CD in Virtualbox Checksum failed

### ISSUE THREAD

**Issue by Mcpower03** [kisslinux/repo#199]
I gave KISS a try in a virtual machine, but low and behold before I even extracted the tarball, the checksum had failed. So maybe an issue with something? Also I tried to extract it anyway, but some of the packages inside were corrupt

**Comment by Mcpower03** [comment]
After trying a few other virtual machines, checksums also fail on those, so may just be a problem with my computer.

**Comment by dylanaraps** [comment]
The checksums verify fine. Are you sure everything downloaded correctly?
