### ISSUE TITLE
perl fails to build 

### ISSUE THREAD

**Issue by eskiq** [kisslinux/repo#201]
perl v5.32.0
checksum mismatch

Can I somehow ignore that checksum and build perl?

**Comment by jedahan** [comment]
try clearing the cache and building again? `kiss b perl` works for me

**Comment by dylanaraps** [comment]
(The cache being `~/.cache/kiss/sources/perl`)

**Comment by eskiq** [comment]
I'm trying to install KISS and while trying to build perl there is checksum mismatch for perl v5.32.0.tar.gz
-ae5d52cb5f90b650985fd8c551eb8cfda7af9e12c9dcf11a185c5af5153ab334
+dd95ce62365c9a9236f5ba12f69d7cae7021df6467093eec955b4debd73e815b
I'm able to build perl when I skip optional stuff about signatures https://k1ss.org/install#3.0
Cleaning cache does not solve the problem

**Comment by dylanaraps** [comment]
OK. I can reproduce. Pushed a fix. Run `kiss u` and `kiss b perl` after clearing cache and it'll work. :+1:

**Comment by dylanaraps** [comment]
Apologies for the delay, I made the fix over an hour ago but GitHub was down.

**Comment by eskiq** [comment]
No problem and thank your for fix :)
