### ISSUE TITLE
Bison fails to compile after recent commit

### ISSUE THREAD

**Issue by josephreynolds1** [kisslinux/repo#206]
Bison fails to compile after recent commit

```
/usr/bin/ld: src/bison-complain.o: in function `complains':
complain.c:(.text+0xaa1): undefined reference to `styled_ostream_set_hyperlink'
/usr/bin/ld: complain.c:(.text+0xad4): undefined reference to `ostream_printf'
/usr/bin/ld: complain.c:(.text+0xae6): undefined reference to `styled_ostream_set_hyperlink'
collect2: error: ld returned 1 exit status
make: *** [Makefile:4328: src/bison] Error 1
-> bison Build failed
-> bison Log stored to /root/.cache/kiss/logs/bison-2020-07-26-00:52-1048
```

**Comment by dylanaraps** [comment]
I cannot reproduce this on my machine or in a clean chroot. Can you send the full log (`/root/.cache/kiss/logs/bison-2020-07-26-00:52-1048`) as well as a list of all packages installed (`kiss l`)?

**Comment by josephreynolds1** [comment]
Here you go

kiss l output:
[installed_packages.txt](https://github.com/kisslinux/repo/files/4978049/installed_packages.txt)

bison log:
[bison_log.txt](https://github.com/kisslinux/repo/files/4978052/bison_log.txt)

**Comment by dylanaraps** [comment]
Please run `kiss u` and then `kiss b bison`. Let me know if the issue still occurs. :+1:

**Comment by josephreynolds1** [comment]
Failed again here is the updated build log.   I updated the other pending packages (git,flatpak ostree, freetype-harfbuzz,harfbuzz-icu)

[installed_packages.txt](https://github.com/kisslinux/repo/files/4984811/installed_packages.txt)

[bison-2020-07-27-14:18-9777.txt](https://github.com/kisslinux/repo/files/4984804/bison-2020-07-27-14.18-9777.txt)

**Comment by dylanaraps** [comment]
To confirm, the previous version can still be built without failure?

**Comment by dylanaraps** [comment]
These are the differences in our `configure` output:

```diff
 checking for perl... /usr/bin/perl
-checking for xsltproc... /usr/bin/xsltproc
+checking for xsltproc... no
 checking for locale.h... yes
 checking for sys/param.h... yes
 checking for sys/socket.h... yes
@@ -357,8 +357,7 @@
 checking whether ldexpl is declared... yes
 checking whether ldexpl() can be used without linking with libm... yes
 checking whether ldexpl works... yes
-checking for libtextstyle... yes
-checking how to link with libtextstyle... -ltextstyle
+checking for libtextstyle... no
 checking for pthread_rwlock_t... yes
 checking whether pthread_rwlock_rdlock prefers a writer to a reader... no
 checking for stdlib.h... (cached) yes
@@ -475,15 +474,15 @@
 checking for getline... yes
 checking for working getline function... yes
 checking whether NLS is requested... no
-checking for msgfmt... /usr/local/bin/msgfmt
-checking for gmsgfmt... /usr/local/bin/msgfmt
-checking for xgettext... /usr/local/bin/xgettext
-checking for msgmerge... /usr/local/bin/msgmerge
+checking for msgfmt... no
+checking for gmsgfmt... :
+checking for xgettext... no
+checking for msgmerge... no
 checking for CFPreferencesCopyAppValue... no
 checking for CFLocaleCopyCurrent... no
 checking whether to use NLS... no
-checking for valgrind... no
-checking Valgrind suppression file...
+checking for valgrind... valgrind
+checking Valgrind suppression file... build-aux/Linux.valgrind
 checking that generated files are newer than configure... done
```

**Comment by dylanaraps** [comment]
What is providing `libtextstyle` on your machine? I believe this is causing the error.

Notice: ```diff
-checking for libtextstyle... yes
-checking how to link with libtextstyle... -ltextstyle
+checking for libtextstyle... no```

**Comment by dylanaraps** [comment]
This issue should now be fixed. Please reopen if this is not the case. :+1:
