### ISSUE TITLE
Feature request for the package manager: Implementation USE flags

### ISSUE THREAD

**Issue by Joe23232** [kisslinux/repo#208]
I wanted to suggest to implement USE flags, that is also found in the Gentoo's portage package manager. That way the system is less bloated with unnecessary dependencies being installed into the system, unless if I am missing something?

**Comment by dylanaraps** [comment]
USE flags will not be implemented as they add a rather messy complexity to each package, the package manager and the format itself. If you would like to customize a package, the recommended way is to fork the package to a repository of your own. If you would really like USE flags, I suggest using Gentoo. 

Repository files can be symbolic links to other repository files. This removes the maintenance burden of forking a package in its entirety. The `kiss fork` and `kiss link` actions are available to automate this for you. 
A simple example: https://github.com/jedavies-dev/kiss-armv7/tree/master/repo/libelf 

The `KISS_HOOK` feature can be used to conditionally control things at runtime. This feature will be extended at a later stage to give more control to the user. Some shuffling around of things internally is needed first. You may find it useful in its current state.
Documentation here: https://k1ss.org/package-manager#6.0 

Thanks for opening this issue.

**Comment by Joe23232** [comment]
> The KISS_HOOK feature can be used to conditionally control things at runtime.

So this is not for build times, only like when running the application, right?

> Thanks for opening this issue.

No worries. Thanks for letting me know :)

---

One thing mate, going off topic over here, but I wanted to know what is the huge difference between Gentoo and kiss Linux other than the package manager? Is it possible for me to install/implement KISS Linux but replace the default package manager with portage instead as you mentioned on your website that there is no specific lock in software? I want to use kiss Linux as I know that it supports runit and musl but Gentoo does not officially support it.

**Comment by dylanaraps** [comment]
I suggest having a read of the website/documentation and a look at the sources. These questions should already be answerable. :+1:

**Comment by Joe23232** [comment]
THanks man.
