### ISSUE TITLE
Proposed changes to chroot tarballs.

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#209]
1. [x] Swap to a versioning scheme based on year and month (likely `YYYY.M`).
2. [ ] Stop providing the repositories in `/var/db/kiss/repo`.
3. [ ] Drop the sub-directory `kiss-chroot` from tarballs.
4. [x] Start putting versions in tarball names. 
5. [x] Drop `kiss_path.sh`.

The first change is pretty straightforward. The current versioning scheme 
carries with it no meaning whatsoever. 

The second change carries the following benefits:

- Reduces size of chroot tarballs (working on numbers).
- Removes idea that `/var/db/kiss/repo` is important in any way.
- User will be introduced more in depth to repositories in the installation guide.
- User will setup repositories how *they* like from the start.
- User can be informed about the Community repository when they setup the official ones.

It carries the following downsides:

- What to do about `/etc/profile.d/kiss_path.sh`. Remove this too? (This makes logical sense to me).
- More setup (I think it's a good thing).
- ???

I'm opening this issue to hear your thoughts. 

**Edit: I've added two more points.**

The third change will make extraction simpler. We actually make use of GNU tar in the installation guide. The change will also remedy this.

**Comment by dylanaraps** [comment]
Before: 
```sh
-> du -sh kiss-chroot.tar.xz
35.3M   kiss-chroot.tar.xz
```

After:

```sh
-> du -sh kiss-chroot.tar.xz
31.3M   kiss-chroot.tar.xz
```

**Comment by sdsddsd1** [comment]
I like the idea to hand the setup of KISS_PATH towards the user and agree with your thoughts.
However how would we deal with a throw-away chroot? Setup KISS_PATH every time?

**Comment by konimex** [comment]
> Stop providing the repositories in `/var/db/kiss/repo`.

So users would have to `git clone` it manually?

**Comment by dylanaraps** [comment]
> So users would have to git clone it manually?

Yes. This would be covered early in the installation guide as a hands-on introduction to repositories. I will also be moving the Community repository information here so someone following the guide can install `nano` (or what have you) before needing to use `vi` (example).

>  However how would we deal with a throw-away chroot? Setup KISS_PATH every time?
Good question. You have a few options (possibly more, need to think about it).

- Copy or symbolically link the host's repositories to the chroot.
- Create your own chroot containing repositories.
- Clone the repositories when you enter the chroot (may not be ideal, depends).

**Comment by jedahan** [comment]
I like removing kiss_path.sh

If users have more setup to do, I would like to see recommended 'defaults' in the documentation

For example, I used to put repos in `~/.cache` but think it makes more sense for most to be in `/var/db/kiss/repo`

If every new kiss user runs the same initial commands (ex: `git clone blah /var/db/kiss/repo`, `echo 'export KISS_PATH=...' >> /etc/profile...`), and you make everyone go through the steps to learn it, I would appreciate the chroot having a motd or default .profile skeleton that says what you should do, something like:

```
Welcome to Kiss!

To get started, try `kiss help quick-start`

To change this message, edit `/etc/motd`
```

**Comment by jedahan** [comment]
Ideally there's even a quicker-quick-start, which would fit in the motd, something like:

```
export KISS_REPOS_PATH=/var/db/kiss/
echo "export KISS_PATH=$KISS_REPOS_PATH/repo/core" > /etc/profile.d/kiss_path.sh
source /etc/profile.d/kiss_path.sh
mkdir -p $KISS_PATH
git clone git://git.k1ss.org/repo $KISS_REPOS_PATH
kiss update
kiss build nano
kiss install nano
nano /etc/motd
```

**Comment by dylanaraps** [comment]
I was going to recommend that users keep repositories in their `$HOME` directory rather than somewhere system-wide. It reduces usage of `root` (or equivalent) and is much easier to work with. Of course, this would just be the example/recommendation. The repositories can be anywhere.

**Comment by jedahan** [comment]
I would love for them to be in the home directory, the only caveat being to make sure doas/sudo integration respects the correct PATH, KISS_PATH, etc - I got bit by having `kiss b/i` resolve different packages between root and user (which is likely due to my own misconfiguration of doas/sudo).

Alternatively, showing how the default install prefix could be in the user directory would also be fantastic. That way different users would see different binaries.

```sh
micro@~
$ kiss b nano && kiss i nano            # installs nano from ~/.cache/kiss/repos/kiss/core to ~/.local/bin, no sudo/doas needed

micro@~
$ sudo kiss b nano && sudo kiss i nano  # installs nano from /var/db/kiss/repo/core to /bin

micro@~
$ sudo -E KISS_PATH kiss b/i nano       # installs nano from ~/.cache/kiss/repos/kiss/core to /bin
```

p.s. let me know if you prefer chatting about this on github or irc, i'm mostly just spitballing

**Comment by dylanaraps** [comment]
I'm online right now in IRC if you'd like to discuss.

**Comment by konimex** [comment]
>I was going to recommend that users keep repositories in their `$HOME` directory rather than somewhere system-wide.

I don't think that's ideal in a possibly multi-user system. But of course, that was just a recommendation/suggestion.

**Comment by mmatongo** [comment]
I've always fancied the Gentoo install process so i'm definitely pro more setup.

**Comment by dilyn-corner** [comment]
> > I was going to recommend that users keep repositories in their `$HOME` directory rather than somewhere system-wide.
> 
> I don't think that's ideal in a possibly multi-user system. But of course, that was just a recommendation/suggestion.

If someone knows their system is multi-seat, they might already have a preferred location that isn't /var anyways. 

I personally love the repository change. It gives a good introduction to how the package system on KISS works, which is arguably one of the most important features of the distro. Not to mention the fact that, next to kernel configuration, how the repository system works is one of the more frequent questions. 
If users don't want to clone the repo on every install, they could always just start keeping their own tarballs; I keep one for KISS-kde in /root; it's a one-and-done and updates are basically just a `kiss u; exit; tar blablabla`.

**Comment by konimex** [comment]
>  Stop providing the repositories in /var/db/kiss/repo.

Say, how do we handle partial fork repositories if we stop hardcoding `/var/db/kiss/repo` as the main KISS Linux repo? Since, two examples, both [kiss-aarch64](https://github.com/jedavies-dev/kiss-aarch64/blob/b53796ec2d369bbbad302666d9a4ff395b8315d3/repo/musl/sources) and [wyverkiss](https://github.com/wyvertux/wyverkiss/blob/41a45bf985ed99e08a52d06367110fe8b6113c63/core/musl/sources) symlinks to a hard (not relative) path.

Also KISS Linux ceases to be KISS Linux if this repo isn't used primarily, *I think*.

**Comment by dylanaraps** [comment]
> Say, how do we handle partial fork repositories if we stop hardcoding /var/db/kiss/repo as the main KISS Linux repo? 

The package manager could possibly just fill in the blanks with the 2nd match from `KISS_PATH` (if it exists).

Example KISS_PATH:

```
export KISS_PATH=/path/to/myrepo:/path/to/repo/core
```

Package in `myrepo` would contain some kind of something to tell the package manager that it is a "layer". Package manager then looks in `core`, finds the package and fills in the blanks. 

Question here is; what's the best way to implement this?

We could possibly do it via broken symlinks. We link the files to some marker for the package manager to resolve. I'm just throwing ideas around but it'd be nice to see what others come up with.

**Comment by sdsddsd1** [comment]
We could introduce  variables for `repo` and `community`. So the symlinks would be protable. Dont know if this makes sense. This looks a bit more complicated.
``` 
export REPO=/path/to/repo/
export COMMUNITY=/path/to/community

export KISS_PATH=/path/to/myrepo:$COMMUNITY/comminity:$REPO/core
```

**Comment by dylanaraps** [comment]
I thought about this issue some more and tried three different approaches. None of these were workable and functionality would regress were we to pick one and roll with it. I believe I have found a solution that requires no changes to the package manager and actually *adds* functionality. I'll first talk about the approaches I tried.


1. Use broken symlinks (`version` -> `LINK/version`)

    The `LINK` directory would be populated at runtime with the repository files from the **2nd match** in `$KISS_PATH`. This is very transparent to the package manager as we're simply *fixing* the links at runtime. This has many issues however. 

    - What if I want to link `pkg-a`'s files to `pkg-b`? This approach limits resolution to `pkg-a -> pkg-a` .
    - How does clean up of this directory work? 
    - We're writing to repositories when we should only be reading from them.
    - What if 2nd match is also symlinks?
    - What if 2nd match is the same as the 1st match (Can happen when using `kiss b` in a package's directory).
    - etc

2. Resolve packages on a file by file basis.

    This is a very intrusive change, requires multiple searches of paths and leaves you wondering where each file actually came from. Again plagued by the same issues as above.

    - How do we handle nesting?
    - What if I want to link `pkg-a`'s files to `pkg-b`? This approach limits resolution to `pkg-a -> pkg-a` .
    - What if 2nd match is also symlinks?
    - What if 2nd match is the same as the 1st match (Can happen when using `kiss b` in a package's directory).
    - etc

3. Create a new cache directory and *construct* the package at runtime.

    This approach would create a "temporary repository" in `~/.cache/kiss/meta-<pid>` which would be deleted once finished. The package manager would copy the required files here, fixing any broken symlinks. Same issues 

    - What if I want to link `pkg-a`'s files to `pkg-b`? This approach limits resolution to `pkg-a -> pkg-a` .
    - What if 2nd match is also symlinks?
    - What if 2nd match is the same as the 1st match (Can happen when using `kiss b` in a package's directory).


What I've come to realize is that the package manager is **the wrong place** for this feature to exist. I propose a solution which does not require code, gives more control to those maintaining semi-linked packages and keeps the existing behavior functional for those who want to use it.

### Solution for repository owners

Use git submodules, pull in the desired repository and symlink relatively to it.

This has a few benefits over the current model.

1. It keeps file access **contained** to the repository.
2. Updates to the kisslinux repositories won't cause breakage as you must manually update submodules.
3. Makes your repository self-contained (no reliance on another repository existing independently in the system).


### Solution for individual packages

As this change requires no code, the original symlink functionality is still there. I recommend using `kiss link` for singular packages in your own personal repositories. This should be no different from before. 

For changes solely to `build` files, it's even easier to use the `pre-build` KISS hook to make your modifications.


----------------

Please let me know your thoughts. :+1:

**Comment by konimex** [comment]
> Updates to the kisslinux repositories won't cause breakage as you must manually update submodules.

Won't the repository owner *lose* advantage of the current model if git-submodule is used if in the end they must update manually?

**Comment by dylanaraps** [comment]
> Won't the repository owner lose advantage of the current model if git-submodule is used if in the end they must update manually?

The repository owner could `git submodule update --remote` on each commit **OR** we could make this the behavior of the package manager during `kiss update`, making the process effectively identical to how it is now. I'll look into what other options we have or if it's possible to make this configurable *in the repository*.

**Comment by dylanaraps** [comment]
Adding my notes here.

---------

This may be desirable for repository owners. It makes the submodule *shallow*. 
```
submodule.<name>.shallow 
```

**Comment by dylanaraps** [comment]
To quickly sum up exactly what needs to be done.

1. Add submodule to your repository.

If you're using the same repository for devel (you're not **just** using it with kiss, ie read-only access, never pushing).

2. Set `git config submodule.<name>.ignore all` (Change `<name>` to submodule name).

**Comment by sdsddsd1** [comment]
So as far as I understand, the submodules for the enduser get updated by the package manager automatically. But does the maintainer also has to update their submodules in the repo every time an update in the original repos happen to make them available for the enduser, or does this also happen automatically?

**Comment by dylanaraps** [comment]
> So as far as I understand, the submodules for the enduser get updated by the package manager automatically.

Yes. 

> But does the maintainer also has to update their submodules in the repo every time an update in the original repos happen to make them available for the enduser, or does this also happen automatically?

No. The user will always have the latest version of the repositories (updated during `kiss u`).

**Comment by sdsddsd1** [comment]
At first this looked a bit complicated, but after trying it out, its pretty straight forward to me.
I played through some scenarios but hit a wall at "Adding a gitlab repo as submodules to my github repo". They are not linked right and not cloned with the repo. I could not test yet "having a gitlab repo and adding a submodule repo from github".

**Comment by dylanaraps** [comment]
@sdsddsd1 They don't *need* to be cloned with the repository as `kiss u` will pull them down anyway. You can clone submodules with the repository by using either `git clone --recurse-submodules` or `git clone --recursive`.

**Comment by mmatongo** [comment]
Had similar sentiments as @sdsddsd1 but it's fairly easy, though for someone with basic git knowledge it would be a learning curve. I also had a bit of trouble linking a gitlab repo as a submodule but it turns out it wasn't properly linked.

**Comment by dylanaraps** [comment]
Everything is in place to push the button on this change. The new installation instructions can be seen here: https://github.com/kisslinux/website/commit/5a0f5c1d106c4df899d1dcea14cbcfdb1174508c

To give repository owners time to switch over (and to extend discussion), this change will be made in two week's time. If there are no qualms before the deadline (and everyone switches prior to it), it may make sense to do the change earlier. We'll see how we go.

**Comment by dylanaraps** [comment]
Wrote about it more here: https://k1ss.org/news/20200811a

**Comment by Admicos** [comment]
Quick question: Wouldn't each repo pulling in submodules separately cause duplication and wasted disk space?

Well, KISS repos _are_ pretty small (in terms of disk space) to begin with, but having the same repo duplicated at least twice still feels like a waste to me.

I can't think of any solutions to this problem right now, but I still feel like this is something worth considering.

**Comment by dylanaraps** [comment]
@Admicos They're shallow clones fwiw. You're also unlikely to have very many (if any) repositories on disk which have a dependence on `/var/db/kiss/repo` (and with this change, a submodule). This is used by architecture forks, glibc KISS, etc and not by the majority of repositories.  This only affects those repositories.

**Comment by dilyn-corner** [comment]
A related question: is there a way we can explicitly specify what submodules in a repository to pull in? 
I ask because if `qt5` attempts to obfuscate their source downloads we have to switch to git sources, and they provide *every* Qt package as a submodule. It makes source fetching take quite a long time.

**Comment by dylanaraps** [comment]
@dilyn-corner The package manager handling of packages *sources* is different to its handling of *repositories*. That being said, I don't think the package manager should resolve submodules in sources. This should be opt-in via build files. Will make the change.

**Comment by dylanaraps** [comment]
Documentation changes to shortly follow. https://github.com/kisslinux/repo/releases/tag/2020.9
