### ISSUE TITLE
Package request: syslinux / systemd-boot

### ISSUE THREAD

**Issue by LucaT1** [kisslinux/repo#21]
In the spirit of keeping things simple, I'd like to install some minimal bootloaders instead of grub which has way too many features compared to what I really need.

- [ ] [syslinux](https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/)
- [ ] [systemd-boot/gummyboot](https://github.com/ivandavidov/systemd-boot)

If these packages are out of the scope of the project, please feel free to close the issue.
I will attempt to build systemd-boot or syslinux once I manage to compile the kernel. If everything goes as expected I'll open a PR.

EDIT: Removed efilinux as it seems just an overhead since both syslinux and systemd-boot handle UEFI booting already.

**Comment by konimex** [comment]
While it is possbile to build `systemd-boot` by itself using the whole `systemd` tarball (see [Gentoo](https://packages.gentoo.org/packages/sys-boot/systemd-boot)), it is possible that we have some proponents of KISS Linux who may reject it. I'm indifferent to it so I can package it, but I'll leave that to others (including in our Discord chat) to decide.

As for `efilinux` and `syslinux`, I'll see what I can do.

**Comment by dylanaraps** [comment]
efibootmgr is included in the main repositories too fyi. You can use this to boot a kernel directly. 

I guess I’m okay with adding systemd-boot etc so long as they live in “public”.

**Comment by LucaT1** [comment]
So I have tried with bot EFISTUBbing and syslinux. With both of them, I couldn't manage to boot properly. Most of the times I get a VFS error because it can't mount the root partition(Tried with both UUID and PARTUUID)(The root partition is in ext4, while /boot is FAT32).I don't understand if it's a problem of the kernel configuration, but I really can't manage to boot.

On the other hand, another problem I run into was that both the efivar and efibootmgr packages don't compile with the new gcc version. I managed to fix efivar by using the git repository as a source(the problem has been fixed but no release has yet been made with [this patch](https://github.com/rhboot/efivar/commit/c3c553db85ff10890209d0fe48fb4856ad68e4e0)). There is also another error in efibootmgr but I haven't yet taken a look at it. Anyway this means I've used another efibootmgr binary from my other linux installations to create the boot entry.

**Comment by dylanaraps** [comment]
Will add the patch to the package and investigate the other issues. Thanks for the detailed bug reports thus far.

**Comment by konimex** [comment]
I've added the `efivar` patches in https://github.com/kissx/packages/commit/380467b7d82914dc3b7223044b146786391c1dfe. However, I can't find the `efibootmgr` bug.

**Comment by LucaT1** [comment]
The patches did the trick. `efibootmgr` now compiles successfully!

I'll see if I can get the system to boot via EFISTUBbing now.

**Comment by LucaT1** [comment]
I'm gonna close this issue as the problem for me currently isn't the bootloader. One I'll get the kernel to work I'll probably use EFISTUBbing.

**Comment by dylanaraps** [comment]
Our kernel config as a whole needs work. I apologize as it hasn't been my current focus.
