### ISSUE TITLE
Last release sha256sum got an extra . (dot)

### ISSUE THREAD

**Issue by motorto** [kisslinux/repo#210]
The last release sha256sum of the tarball have an extra dot on the name of the file of checksum making it impossible to check the checksum without modifying the file.
It probably is confusing because of my english but just want to let you know 

`
6ca39d43c2703fbe2c525bf1edb5b7dac4482e1c5c270132717069264edd1947  kiss-chroot.tar.xz.
`

>  kiss-chroot.tar.xz.

Referring here the extra dot

**Comment by dylanaraps** [comment]
Fixed, apologies.
