### ISSUE TITLE
libelf 0.180-1 fails to build

### ISSUE THREAD

**Issue by josephreynolds1** [kisslinux/repo#211]
latest libelf 0.180-1 version fails to build

**installed packages:**
[installed_packages.txt](https://github.com/kisslinux/repo/files/5010392/installed_packages.txt)

**build log:**
[libelf-2020-08-01-04:50-16977.txt](https://github.com/kisslinux/repo/files/5010394/libelf-2020-08-01-04.50-16977.txt)

**Comment by dylanaraps** [comment]
This is merely... `cc1: all warnings being treated as errors`. Will push a fix in a second. :+1:
