### ISSUE TITLE
wpa_supplicant: install manpages

### ISSUE THREAD

**Issue by noocsharp** [kisslinux/repo#214]
The wpa_supplicant tarball comes with manpages but no make targets to install them. If you add the following in the build script, it will install them properly:
```
# Install manpages
mkdir -p "$1/usr/share/man/man8"
mkdir -p "$1/usr/share/man/man5"
cp doc/docbook/*.8 "$1/usr/share/man/man8"
cp doc/docbook/*.5 "$1/usr/share/man/man5"
```

**Comment by mmatongo** [comment]
Alternatively

`install -Dm644 doc/docbook/*.8 "$1/usr/share/man/man8"`
`install -Dm644 doc/docbook/*.5 "$1/usr/share/man/man5"`

**Comment by noocsharp** [comment]
Yeah, `install` is probably the best way to do it. 

I don't think bloat is the reason it is excluded. There was a discussion about man pages at #90 regarding LibreSSL which has many thousands of manpages. All of the LibreSSL manpages are included now, probably unnecessary for most people. Adding 8 arguably more useful manpages seems acceptable by this heuristic. For wpa_supplicant, they were probably excluded because they aren't installed by default and nobody has asked for them until now.

**Comment by mmatongo** [comment]
You have a point there.

**Comment by dylanaraps** [comment]
@noocsharp You're exactly right.
