### ISSUE TITLE
Grub Error, unable to install

### ISSUE THREAD

**Issue by naurias** [kisslinux/repo#219]
I am trying to install KISS but have no luck with grub so I am opening an issue here.
Here is what I get

`grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=kiss`

`Installing for x86_64-efi platform.`

`grub-install: warning: cannot open directory '/usr/share/locale': No such file or directory.`

`modprobe: can't change directory to '/lib/modules': No such file or directory`

`Installation finished. No error reported.
`

I followed all the steps and have baseinit installed but somehow i cant figure it out
I haven't installed firmware modules however in my previous attempts when i did install firmware modules the error was 
`modprobe: can't change directory to '5.8.8-arch1-1: No such file or directory`
which is the kernel of liveusb

**Comment by dylanaraps** [comment]
```
grub-install: warning: cannot open directory '/usr/share/locale': No such file or directory.
```

This is harmless. 

```
modprobe: can't change directory to '/lib/modules': No such file or directory
```

This depends on whether you have modules or not. Also harmless.

```
Installation finished. No error reported. 
```

This tells me grub was installed without issue.

**Comment by dylanaraps** [comment]
What is the issue exactly?

**Comment by naurias** [comment]
sorry for incomplete explanation as I'm not sure what to provide. There's no grub entry so i can't boot into KISS (although grub config detects vmlinuz and  it's in grub.cfg)

**Comment by arvl130** [comment]
Do you have it generated in the right directory? The grub config should be in `/boot/grub/grub.cfg`.

Btw support questions like this are probably better handled on the IRC. Lots more people can help you there

**Comment by naurias** [comment]
> Do you have it generated in the right directory? The grub config should be in `/boot/grub/grub.cfg`.
 
Yes i did
> Btw support questions like this are probably better handled on the IRC. Lots more people can help you there

Ok, I'll try there
