### ISSUE TITLE
efibootmgr fails to build

### ISSUE THREAD

**Issue by periish** [kisslinux/repo#220]
https://termbin.com/6t40
Fails to build with latest GCC and binutils.

**Comment by dylanaraps** [comment]
This log is for `efivar` and I can reproduce when my `CFLAGS` are set to `-O3 -flto`.

**Comment by dylanaraps** [comment]
Fix is simply: `-flto -flto-partition=none`.

Use a `KISS_HOOK` (or other means) to set this additional option for the build of `efivar`.

**Comment by dylanaraps** [comment]
https://github.com/rhboot/efivar/issues/156

**Comment by periish** [comment]
:v My cflags were empty.

**Comment by dylanaraps** [comment]
Found the issue. If your `CFLAGS` are empty, `efivar` sets them to `-O2 -flto -g3`. Will push a fix.

**Comment by periish** [comment]
That's funny, they pushed cflags that broke their own package.

**Comment by Ahlam505** [comment]
> خطأ المنبع: [rhboot / efivar # 156](https://github.com/rhboot/efivar/issues/156)
