### ISSUE TITLE
libxcb fails to build

### ISSUE THREAD

**Issue by McFranko** [kisslinux/repo#221]
I followed the instructions for installation and ran `kiss b xorg-server xinit xf86-input-libinput`

The first package it tried to compile was libxcb, which failed, saying
`cb_auth.c:33:10: fatal error: X11/Xauth.h: No such file or directory
   33 | #include <X11/Xauth.h>
      |          ^~~~~~~~~~~~~`
Anyone encountered this issue before?

Here is the full log:
`
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a Python interpreter with version >= 2.6... python
checking for python... /usr/bin/python
checking for python version... 3.8
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.8/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.8/site-packages
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-musl
checking host system type... x86_64-pc-linux-musl
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-pc-linux-musl/bin/ld
checking if the linker (/usr/x86_64-pc-linux-musl/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 98304
checking how to convert x86_64-pc-linux-musl file names to x86_64-pc-linux-musl format... func_convert_file_noop
checking how to convert x86_64-pc-linux-musl file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-musl/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
./configure: line 1: /usr/bin/file: not found
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-pc-linux-musl/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc option to accept ISO C99... none needed
checking whether __clang__ is declared... no
checking whether __INTEL_COMPILER is declared... no
checking whether __SUNPRO_C is declared... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking if gcc supports -Werror=unknown-warning-option... no
checking if gcc supports -Werror=unused-command-line-argument... no
checking if gcc supports -Wall... yes
checking if gcc supports -Wpointer-arith... yes
checking if gcc supports -Wmissing-declarations... yes
checking if gcc supports -Wformat=2... yes
checking if gcc supports -Wstrict-prototypes... yes
checking if gcc supports -Wmissing-prototypes... yes
checking if gcc supports -Wnested-externs... yes
checking if gcc supports -Wbad-function-cast... yes
checking if gcc supports -Wold-style-definition... yes
checking if gcc supports -Wdeclaration-after-statement... yes
checking if gcc supports -Wunused... yes
checking if gcc supports -Wuninitialized... yes
checking if gcc supports -Wshadow... yes
checking if gcc supports -Wmissing-noreturn... yes
checking if gcc supports -Wmissing-format-attribute... yes
checking if gcc supports -Wredundant-decls... yes
checking if gcc supports -Wlogical-op... yes
checking if gcc supports -Werror=implicit... yes
checking if gcc supports -Werror=nonnull... yes
checking if gcc supports -Werror=init-self... yes
checking if gcc supports -Werror=main... yes
checking if gcc supports -Werror=missing-braces... yes
checking if gcc supports -Werror=sequence-point... yes
checking if gcc supports -Werror=return-type... yes
checking if gcc supports -Werror=trigraphs... yes
checking if gcc supports -Werror=array-bounds... yes
checking if gcc supports -Werror=write-strings... yes
checking if gcc supports -Werror=address... yes
checking if gcc supports -Werror=int-to-pointer-cast... yes
checking if gcc supports -Werror=pointer-to-int-cast... yes
checking if gcc supports -pedantic... yes
checking if gcc supports -Werror... yes
checking if gcc supports -Werror=attributes... yes
Package xorg-macros was not found in the pkg-config search path.
Perhaps you should add the directory containing `xorg-macros.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xorg-macros', required by 'virtual:world', not found
checking whether make supports nested variables... (cached) yes
checking whether to build developer documentation... yes
checking for doxygen... no
configure: WARNING: doxygen not found - documentation targets will be skipped
configure: WARNING: dot not found - doxygen targets will be skipped
checking for CHECK... no
checking for XCBPROTO... yes
checking for NEEDED... yes
checking for XDMCP... no
no
checking XCBPROTO_XCBINCLUDEDIR... //usr/share/xcb
checking XCBPROTO_XCBPYTHONDIR... //usr/lib/python3.8/site-packages
checking for ANSI C header files... (cached) yes
checking for library containing getaddrinfo... none required
checking for library containing connect... none required
checking for library containing sendmsg... none required
checking for struct msghdr.msg_control... yes
checking for struct sockaddr_un.sun_len... no
checking tsol/label.h usability... no
checking tsol/label.h presence... no
checking for tsol/label.h... no
checking for is_system_labeled... no
checking whether IOV_MAX is declared... yes
checking whether gcc supports symbol visibility... yes
checking for getaddrinfo... yes
checking for poll... yes
checking for launchd... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating man/Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating xcb.pc
config.status: creating xcb-composite.pc
config.status: creating xcb-damage.pc
config.status: creating xcb-dpms.pc
config.status: creating xcb-dri2.pc
config.status: creating xcb-dri3.pc
config.status: creating xcb-ge.pc
config.status: creating xcb-glx.pc
config.status: creating xcb-present.pc
config.status: creating xcb-randr.pc
config.status: creating xcb-record.pc
config.status: creating xcb-render.pc
config.status: creating xcb-res.pc
config.status: creating xcb-screensaver.pc
config.status: creating xcb-shape.pc
config.status: creating xcb-shm.pc
config.status: creating xcb-sync.pc
config.status: creating xcb-xevie.pc
config.status: creating xcb-xf86dri.pc
config.status: creating xcb-xfixes.pc
config.status: creating xcb-xinerama.pc
config.status: creating xcb-xinput.pc
config.status: creating xcb-xkb.pc
config.status: creating xcb-xprint.pc
config.status: creating xcb-xselinux.pc
config.status: creating xcb-xtest.pc
config.status: creating xcb-xv.pc
config.status: creating xcb-xvmc.pc
config.status: creating doc/xcb.doxygen
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands

  Package: libxcb 1.14

  Configuration
    XDM support.........: no
    sendmsg fd passing..: yes
    Build unit tests....: no
      with html results.: no
    XCB buffer size.....: 16384

  X11 extensions
    Composite...........: yes
    Damage..............: yes
    Dpms................: yes
    Dri2................: yes
    Dri3................: yes
    GenericEvent........: no
    Glx.................: yes
    Randr...............: yes
    Record..............: yes
    Render..............: yes
    Resource............: yes
    Screensaver.........: yes
    selinux.............: no
    Shape...............: yes
    Shm.................: yes
    Sync................: yes
    Xevie...............: no
    Xfixes..............: yes
    Xfree86-dri.........: yes
    xinerama............: yes
    xinput..............: yes
    xkb.................: yes
    xprint..............: no
    xtest...............: yes
    xv..................: yes
    xvmc................: yes

  Used CFLAGS:
    CPPFLAGS............:
    CFLAGS..............: -O3 -pipe -march=native

  Installation:
    Prefix..............: /usr

Making all in src
make[1]: Entering directory '/home/fronkles/.cache/kiss/build-33844/libxcb/src'
  GEN      xproto.c
  GEN      bigreq.c
  GEN      xc_misc.c
  GEN      composite.c
  GEN      damage.c
  GEN      dpms.c
  GEN      dri2.c
  GEN      dri3.c
  GEN      present.c
  GEN      glx.c
  GEN      randr.c
  GEN      record.c
  GEN      render.c
  GEN      res.c
  GEN      screensaver.c
  GEN      shape.c
  GEN      shm.c
  GEN      sync.c
  GEN      xevie.c
  GEN      xf86dri.c
  GEN      xfixes.c
  GEN      xinerama.c
  GEN      xinput.c
  GEN      xkb.c
  GEN      xprint.c
  GEN      xselinux.c
  GEN      xtest.c
  GEN      xv.c
  GEN      xvmc.c
  GEN      ge.c
make  all-am
make[2]: Entering directory '/home/fronkles/.cache/kiss/build-33844/libxcb/src'
  CC       xcb_conn.lo
  CC       xcb_out.lo
  CC       xcb_in.lo
  CC       xcb_ext.lo
  CC       xcb_xid.lo
  CC       xcb_list.lo
  CC       xcb_util.lo
  CC       xcb_auth.lo
xcb_auth.c:33:10: fatal error: X11/Xauth.h: No such file or directory
   33 | #include <X11/Xauth.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:1034: xcb_auth.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/fronkles/.cache/kiss/build-33844/libxcb/src'
make[1]: *** [Makefile:800: all] Error 2
make[1]: Leaving directory '/home/fronkles/.cache/kiss/build-33844/libxcb/src'
make: *** [Makefile:792: all-recursive] Error 1
`

If you have any other questions lmk

**Comment by sdsddsd1** [comment]
You are missing `Xauth.h` which is provided by the package `libXau` which in return is in the depends file of libxcb. Sometimes a dependency is not pulled in early enough. Just try to build again and libxcb should build without error.

**Comment by McFranko** [comment]
Thank you!
