### ISSUE TITLE
Rust fails to builld on a clean chroot

### ISSUE THREAD

**Issue by arvl130** [kisslinux/repo#224]
Trying to build `rust` on a clean KISS chroot leads to this error during build:

       Compiling serde_derive v1.0.106
       Compiling globset v0.4.3
       Compiling env_logger v0.7.1
    error: failed to run custom build command for `openssl-sys v0.9.54`
    
    Caused by:
      process didn't exit successfully: `/root/.cache/kiss/build-5231/rust/build/i686-unknown-linux-musl/stage2-tools/release/build/openssl-sys-b269d9b220f5a0ca/build-script-main` (exit code: 101)
      --- stdout
      cargo:rustc-cfg=const_fn
      cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
      I686_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR unset
      cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
      OPENSSL_LIB_DIR unset
      cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
      I686_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR unset
      cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
      OPENSSL_INCLUDE_DIR unset
      cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_MUSL_OPENSSL_DIR
      I686_UNKNOWN_LINUX_MUSL_OPENSSL_DIR unset
      cargo:rerun-if-env-changed=OPENSSL_DIR
      OPENSSL_DIR unset
      run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"
    
      --- stderr
      thread 'main' panicked at '
    
      Could not find directory of OpenSSL installation, and this `-sys` crate cannot
      proceed without this knowledge. If OpenSSL is installed and this crate had
      trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
      compilation process.
    
      Make sure you also have the development packages of openssl installed.
      For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
    
      If you're in a situation where you think the directory *should* be found
      automatically, please open a bug at https://github.com/sfackler/rust-openssl
      and include information about your system as well as this message.
    
      $HOST = i686-unknown-linux-musl
      $TARGET = i686-unknown-linux-musl
      openssl-sys = 0.9.54
    
      ', /root/.cache/kiss/build-5231/rust/vendor/openssl-sys/build/find_normal.rs:150:5
    command did not execute successfully: "/root/.cache/kiss/build-5231/rust/bin/cargo" "build" "--target" "i686-unknown-linux-musl" "-Zbinary-dep-depinfo" "-j" "1" "--release" "--locked" "--frozen" "--manifest-path" "/root/.cache/kiss/build-5231/rust/src/tools/cargo/Cargo.toml" "--message-format" "json-render-diagnostics"
    expected success, got: exit code: 101
    failed to run: /root/.cache/kiss/build-5231/rust/build/bootstrap/debug/bootstrap build -j 1
    Build completed unsuccessfully in 4:36:29

Installing `pkgconf` or defining `OPENSSL_DIR` should fix this error like mentioned. My fork already includes this change, though I suppose I should report here as well.

**Comment by arvl130** [comment]
Did we really need to add a new dependency? Shouldn't defining `OPENSSL_DIR` be enough? I'm just curious as to why this approach was taken, since I'll be mirroring this in my fork.

**Comment by dylanaraps** [comment]
This is a compile time dependency on a 300kb utility (used by 70 or so packages). pkgconf was recently changed from an implicit dependency (was also part of core) to an explicit one. It was always installed till recently and rust always used it in other words (and I missed this package when doing the transition). 

It is also listed as a dependency in the README file of rustc, rls, etc. Although, through poking around the sources, setting `OPENSSL_DIR` should be enough to avoid pkgconf. I'm in the middle of moving house but will investigate whether or not it makes sense to avoid pkgconf here when I have more time. 

There's also a pkg-config crate that is pulled in but this seems to gracefully handle the absence of pkgconf.
