### ISSUE TITLE
unbreak firefox-esr build with rustc/cargo v1.47.0

### ISSUE THREAD

**Issue by mssx86** [kisslinux/repo#229]
not a kiss user but i check your repo every once in a while when things go wrong with my system. the patch [in this commit of yours](https://github.com/kisslinux/repo/commit/74afd902b1c0b7bbb267e97fd2c5dbdf87b30b8) applies to `firefox-78.3.1esr` but firefox fails to build, first because of checksum difference, then some odd cargo error if the checksums are cleared.

certain patches from the gentoo mozilla team addresses the issue in this tarball: http://gentoo-mirror.alexxy.name/distfiles/62/firefox-esr-78-patches-03.tar.xz (it's the `firefox-esr-78-patches-03.tar.xz` mentioned in the ebuild, you can check [this commit in gentoo commit logs for firefox](https://gitweb.gentoo.org/repo/gentoo.git/commit/www-client/firefox?id=47215932e1eea3bdea27c13ce9b422e7116005de), commit also includes a checksum for my link.).

patches that address the issue in the said tarball are:
```
0036-bmo-1643201-Cherry-pick-some-servo-changes-to-derive.patch
0037-bmo-1653339-Teach-style_derive-s-map_type_params-abo.patch
0038-bmo-1663715-Update-syn-and-proc-macro2-so-that-Firef.patch
```

you might want to consider adding these to your `firefox-esr` recipe.

wishing every kiss user a good day. have a good one.

**Comment by dylanaraps** [comment]
Thanks for opening this issue. Will apply the patches and have the resulting package live in the testing repository until I have the time to spin up some builds. Users can test in the meantime if they're willing.
