### ISSUE TITLE
firefox 81 build issue

### ISSUE THREAD

**Issue by jedahan** [kisslinux/repo#231]
python 3.9
llvm 10
rust 1.47

The build fails with a trace in `python/mozbuild/mozbuild/configure/__init__.py`

I tried commenting out the loop since it looked like `arg` was `nil`, but then ran into a "missing libpulse" error

I don't think libpulse is in core/extra/community so basically wanna check in, is firefox 81 supposed to be buildable?

I am upgrading to llvm 11 and rust 1.47-2 and will re-try.

I will then test with `--enable-default-toolkit=cairo-gtk3-wayland`

**Comment by dylanaraps** [comment]
Could be a Python 3.9 issue. Will see if I can reproduce.

**Comment by dylanaraps** [comment]
Firefox 82 has been released. Will have this resolved by tomorrow. Apologies for the delay.

**Comment by dylanaraps** [comment]
Also, regarding messages in IRC about firefox-bin and Wayland; The Firefox binaries I provide are only for Xorg (as this is the only  officially supported display server). These binaries cannot work under wayland. If it's possible to create hybrid binaries (**that don't add a runtime dependency on wayland for Xorg users**), I will be happy to do so for our -bin packages.

**Comment by dylanaraps** [comment]
```
python 3.9
llvm 10
rust 1.47
```

Add `nodejs 15.0.0` to the list of rapidly changing Firefox dependencies. Let's pray that everything is compatible this month!

**Comment by dylanaraps** [comment]
Firefox 82 has been pushed to extra.
