### ISSUE TITLE
gtk+3 build failing 

### ISSUE THREAD

**Issue by mmatongo** [kisslinux/repo#232]
I was trying to install firefox-bin and encountered this
problem when it came to building gtk+3.

```
grep: /usr/lib/libfontconfig.la: No such file or directory
sed: /usr/lib/libfontconfig.la: No such file or directory
libtool:   error: '/usr/lib/libfontconfig.la' is not a valid libtool archive
make[4]: *** [Makefile:1219: libgdk-3.la] Error 1
make[4]: Leaving directory '/home/dm/.cache/kiss/build-27551/gtk+3/gdk'
make[3]: *** [Makefile:1715: all-recursive] Error 1
make[3]: Leaving directory '/home/dm/.cache/kiss/build-27551/gtk+3/gdk'
make[2]: *** [Makefile:1138: all] Error 2
make[2]: Leaving directory '/home/dm/.cache/kiss/build-27551/gtk+3/gdk'
make[1]: *** [Makefile:750: all-recursive] Error 1
make[1]: Leaving directory '/home/dm/.cache/kiss/build-27551/gtk+3'
make: *** [Makefile:623: all] Error 2
```
Full log file is [here](https://0x0.st/iGIB.txt)

**Comment by dylanaraps** [comment]
Do you have any `.la` files in `/usr/lib`? I cannot reproduce.

**Comment by mmatongo** [comment]
Yes, I do.
Running `find /usr/lib/ -name "*.la"` revealed these.

```
/usr/lib/libevent_openssl.la
/usr/lib/libpixman-1.la
/usr/lib/libass.la
/usr/lib/libevent_pthreads.la
/usr/lib/libevent.la
/usr/lib/libXinerama.la
/usr/lib/libXext.la
/usr/lib/libmp3lame.la
/usr/lib/libevent_extra.la
/usr/lib/libXrandr.la
/usr/lib/libXdamage.la
/usr/lib/libevent_core.la
/usr/lib/libogg.la
/usr/lib/libXss.la
/usr/lib/libopus.la
```

**Comment by dylanaraps** [comment]
Deleting all of these files will solve the issue. The package manager explicitly gets rid of these post-build. I'm unsure as to how they've ended up on your machine.

**Comment by mmatongo** [comment]
Strange that it didn’t, I’ll report back.

**Comment by dylanaraps** [comment]
Send an uploaded build log if the error has changed.

**Comment by mmatongo** [comment]
Deleting the files made it easy but I have encountered another problem now, I was building `firefox-bin` when `gtk+3` failed.
A few problems, there was no build log generated so I'm building it again to generate a log.

running firefox produces the following error/s;
`[1]    11414 illegal hardware instruction  firefox`

**Comment by mmatongo** [comment]
I'll report back when I have something to deliver.

**Comment by mmatongo** [comment]
Nothing came out of this, closing issue.
