### ISSUE TITLE
Mesa failing to build with python 3.9

### ISSUE THREAD

**Issue by Xeno-Hypster** [kisslinux/repo#241]
[log](https://termbin.com/0svf)

@dylanaraps 

Not sure if this is the exact cause, but seems python is the issue here!

**Comment by dylanaraps** [comment]
KISS' python is in `/usr/bin` (as are all binaries). I'm not sure where this `/usr/local/bin/python` came from. Our mesa builds fine with the latest mesa and I cannot reproduce.

```
Program python3 found: YES (/usr/local/bin/python3)
```

**Comment by Xeno-Hypster** [comment]
Ah, no worries. I'll dig around my stuff and see if I can fix my stuff then! Cheers for looking.
