### ISSUE TITLE
xf86-video-intel segfaults when built with clang

### ISSUE THREAD

**Issue by trbednarzyk** [kisslinux/repo#242]
This'll be a **lot** easier than busybox - just apply [this patch](https://gitlab.freedesktop.org/E5ten/xf86-video-intel/commit/a92ccaf05efe8f11b3c5cd217d48ad3cf4caa090) and it's fixed.

[Relevant issue](https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel/-/issues/171).

**Comment by konimex** [comment]
Is this GPU-specific? Since I never reproduced this issue on my Intel GPU laptop.

**Comment by trbednarzyk** [comment]
Are you using i915 with `sna` acceleration?

**Comment by trbednarzyk** [comment]
Regardless, this patch just sets some uninitialized variables to `NULL` so this won't be harmless for anyone who didn't have this issue.

**Comment by dylanaraps** [comment]
Note: The official repositories and community will never fully support GCC-less systems. The officially supported compiler is GCC. The only reason the official repositories contain LLVM/clang is that they're unavoidable for mesa, firefox and rust. If we didn't
need LLVM/clang, they wouldn't be around at all. This is also why I'm reluctant to merge clang fixes. 

1. I cannot properly test clang-only patches, issues, etc.
2. It's an extra maintenance burden (this patch has been sitting unmerged for a year, I'll likely be carrying it around for even longer). 
3. I don't really care for LLVM/clang so it's a waste of my time. 
4. I don't want to debug toolchain issues for a different toolchain. 

Don't expect any more of these patches/issues to be fixed. Wyverkiss is a much better place for these changes.

**Comment by trbednarzyk** [comment]
That's fine. I was originally surprised that you were doing anything with busybox at all yesterday, and that was the only reason I thought it fine to open the last two issues.

The reason I hadn't gone to wyverkiss itself is because I don't care about going as GNU-less as possible, which seems to be the primary aim of the project.

I too don't much care for LLVM/clang but it seems to be more unavoidable than GCC and I hate having two large compilers for the same languages installed on the same system. If I could have only GCC then I would.
