### ISSUE TITLE
Rust fails to build on gcc-less systems

### ISSUE THREAD

**Issue by trbednarzyk** [kisslinux/repo#243]
Potential fix: https://github.com/wyvertux/rust-build

**Comment by konimex** [comment]
Yeah I don't think this would be possible to merge as my rust build links dynamically to libc++.

**Comment by trbednarzyk** [comment]
I also just tried to build the wyverkiss `rust` package and got an error for loading the shared library `libgcc_s.so.1`.
It also had some checksums issues.

**Comment by konimex** [comment]
From https://github.com/wyvertux/rust-build/releases/download/1.46.0/rustc-1.46.0-x86_64-unknown-linux-musl.tar.xz

```
~/.cache/kiss/sources/rust/rustc-1.46.0-x86_64-unknown-linux-musl/rustc/bin $ ldd rustc 
	/lib/ld-musl-x86_64.so.1 (0x7fa57d549000)
	librustc_driver-86a42397d315e812.so => ./../lib/librustc_driver-86a42397d315e812.so (0x7fa5777c6000)
	libstd-84a22de9304f0f12.so => ./../lib/libstd-84a22de9304f0f12.so (0x7fa5776cb000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7fa57d549000)
	libz.so.1 => /lib/libz.so.1 (0x7fa5776a9000)
	libc++.so.1 => /lib/libc++.so.1 (0x7fa5775da000)
	libc++abi.so.1 => /lib/libc++abi.so.1 (0x7fa577598000)
	libunwind.so.1 => /lib/../lib/libunwind.so.1 (0x7fa577589000)
```

If you're already using a Wyverkiss repo (at least for rust), the checksums issue may happen because you still have the bootstrap tarball from KISS in your cache.

**Comment by trbednarzyk** [comment]
Oops, you were right. I deleted the file from the cache and it appears to be building fine now.

**Comment by dylanaraps** [comment]
Note: GCC-less is not something I officially support here. The official repositories are based around GCC as the default compiler (and this is likely? why wyverkiss exists in the first place). I'm not going to pull in every wyverkiss patch or fix every non-GCC issue. Sure, trivial fixes (like the recent busybox commits) are fine but getting something like Rust to build is out of scope.

**Comment by konimex** [comment]
> (and this is likely? why wyverkiss exists in the first place)

That's correct. Wyverkiss (and kiss-llvm, actually, per the `libelf` precedent) is a much better place to handle *patch*-level fixes (while making something `$CC`-neutral because the build system sucks is good enough to be submitted here). I should add a disclaimer to the kiss-llvm READMEs.

I think you can drop the xf86-video-intel patch. I'll take it over to both wyverkiss and kiss-llvm since the package itself is never versioned anyway.
