### ISSUE TITLE
rust build fails

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/repo#246]
libressl patch related
https://termbin.com/ugpq6

**Comment by mssx86** [comment]
i don't use kiss but i also build `rust` with `libressl`, i've used this and got a successful build, it simply is the same patch but i just bumped the 2's to 3's so you might want to try to see if it fixes the issue on your end:
```diff
diff --git a/vendor/openssl-sys/build/main.rs b/vendor/openssl-sys/build/main.rs
index 49f26d2b7..27deb1f36 100644
--- a/vendor/openssl-sys/build/main.rs
+++ b/vendor/openssl-sys/build/main.rs
@@ -221,6 +221,8 @@ See rust-openssl README for more information:
             (3, 1, 0) => ('3', '1', '0'),
             (3, 1, _) => ('3', '1', 'x'),
             (3, 2, 0) => ('3', '2', '0'),
+            (3, 3, 0) => ('3', '3', '0'),
+            (3, 3, _) => ('3', '3', 'x'),
             _ => version_error(),
         };

```

**Comment by depsterr** [comment]
> i don't use kiss but i also build `rust` with `libressl`, i've used this and got a successful build, it simply is the same patch but i just bumped the 2's to 3's so you might want to try to see if it fixes the issue on your end:
> 
> ```diff
> diff --git a/vendor/openssl-sys/build/main.rs b/vendor/openssl-sys/build/main.rs
> index 49f26d2b7..27deb1f36 100644
> --- a/vendor/openssl-sys/build/main.rs
> +++ b/vendor/openssl-sys/build/main.rs
> @@ -221,6 +221,8 @@ See rust-openssl README for more information:
>              (3, 1, 0) => ('3', '1', '0'),
>              (3, 1, _) => ('3', '1', 'x'),
>              (3, 2, 0) => ('3', '2', '0'),
> +            (3, 3, 0) => ('3', '3', '0'),
> +            (3, 3, _) => ('3', '3', 'x'),
>              _ => version_error(),
>          };
> ```

@dylanaraps would be great if you added this patch to the rust build
