### ISSUE TITLE
dhcpcd checksum mismatch

### ISSUE THREAD

**Issue by chopin2712** [kisslinux/repo#255]
When I run

```sh
kiss build dhcpcd
```

I get:

```
ERROR Checksum mismatch with: dhcpcd 
```

Can you help me?

**Comment by mmatongo** [comment]
Navigate to the folder containing the repo, then go to the `dhcpcd` folder and run the command `kiss c`.

This should fix your problem.

Also consider switching repos to, https://github.com/kiss-community/ repos

**Comment by mmatongo** [comment]
Kindly close the issue if your problem was resolved.

**Comment by zQueal** [comment]
Confirmed running `kiss c` in `/var/db/kiss/repo/extra/dhcpcd` fixes this issue.
