### ISSUE TITLE
gcc: install c99 as executeable

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/repo#258]
The new install method does not install c99 as executeable.  https://github.com/kisslinux/repo/blob/master/core/gcc/build#L66. So a build like libudev-zero fails.   
The new tarball is also affected.

**Comment by dylanaraps** [comment]
Thanks. On it.

**Comment by dylanaraps** [comment]
https://github.com/kisslinux/repo/releases/tag/2021.7-2
