### ISSUE TITLE
Import fixes from kiss-community

### ISSUE THREAD

**Issue by git-bruh** [kisslinux/repo#261]
Hi, the changes made in the following commits from the kiss-community repo are missing here:

https://github.com/kiss-community/repo/commit/8181c947f6a8d54a7f79538476d380205b105c6b

https://github.com/kiss-community/repo/commit/75157cd5db2b0a34700d7b643113c6e157198229

https://github.com/kiss-community/repo/commit/8ce6a433396620b5bb85081d90dc803c5eaf1e27﻿

**Comment by dylanaraps** [comment]
I'm sure there's more, haven't looked at kiss-community/repo. 

Thanks for the issue. :)

I've pushed the first two changes. Just waiting for gcc to compile before I push the third.
