### ISSUE TITLE
python 3.10 drops support for libressl

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#263]
See: 

- https://www.python.org/dev/peps/pep-0644/
- https://lwn.net/Articles/841685/
- https://lwn.net/Articles/841664/
- https://github.com/void-linux/void-packages/issues/20935
- https://github.com/libressl-portable/portable/issues/617
- https://discuss.python.org/t/pep-644-require-openssl-1-1-or-newer/5584 (scroll to libressl support).
- https://hardenedbsd.org/article/shawn-webb/2018-04-30/hardenedbsd-switching-back-openssl
- https://www.gentoo.org/support/news-items/2021-01-05-libressl-support-discontinued.html
- https://bugs.python.org/issue43669

There are a few options:

1. Patch libressl support back in.
2. Swap to openssl.
3. Stay on Python 3.9.X (upstream support lasts 5 years iirc).

Keep in mind that openssl depends on perl during build time. This would bring
perl into `core` which I'm not pleased about. (edit: *working on perl removal*)

The one benefit openssl would bring is a reduction in build times and package
size for nodejs. What happens right now is that nodejs compiles its own openssl
and statically links it (as it has no libressl support).

**Comment by konimex** [comment]
Since I'm pretty sure the perl dependency will be a makedep instead of
a true dependency, do we *really* need perl in `core`?

>The one benefit openssl would bring is a reduction in build times and package
> size for nodejs. What happens right now is that nodejs compiles its own openssl
> and statically links it (as it has no libressl support).

Also one less patch to maintain for Rust in case they forget to bump
their openssl-sys.

Anyway, IIRC OpenSSL doesn't provide CA certificates like LibreSSL, we
probably would need to bring back ca-certificates.

**Comment by dylanaraps** [comment]
> Anyway, IIRC OpenSSL doesn't provide CA certificates like LibreSSL, we
probably would need to bring back ca-certificates.

We use curl's ca bundle (which we update on post-install). I don't think we
need to do anything other than adding the equivalent to the openssl package.

> do we really need perl in core?

No, you're right. It can remain in extra. I will be working on removal of the
perl dependency anyway. (But worst case this isn't a blocker).

**Comment by onodera-punpun** [comment]
It seems pretty much every distro is going back to openssl; Gentoo, alpine, void. Especially for a source distro I think ease of porting software is more important than the benefits of libressl (f there even are any)

**Comment by dylanaraps** [comment]
NOTE: We have until October (3.10.0 final: Monday, 2021-10-04) to make this change. 

https://www.python.org/dev/peps/pep-0619/

**Comment by dylanaraps** [comment]
> Anyway, IIRC OpenSSL doesn't provide CA certificates like LibreSSL, we
probably would need to bring back ca-certificates.

Using openssl right now. Can confirm no need for CA certificates.

**Comment by dylanaraps** [comment]
The openssl changes can be seen here: #266.

**Comment by dylanaraps** [comment]
The openssl changes can be seen here: #266.

**Comment by dylanaraps** [comment]
I will be making this change sooner rather than later.
