### ISSUE TITLE
manual page consistency

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#273]
Packages should be consistent regarding their manual pages. Right now, things are a little messy. Some packages provide them in generated form while others require specific tooling for generation. In the latter case we pretend the manuals do not exist. For *some* libraries with many manual pages (open/libressl, etc), we currently disable them.  There's no consistency in other words. 

The ideal situation is as follows:

1. All packages provide manual pages.
2. Users can choose whether or not to install manual pages via KISS_HOOK. 
    - Availability of this option should be made as obvious as possible.
    - See: https://kisslinux.xyz/package-manager#6.2
3. No extra dependencies when user chooses not to install manual pages.

This is going to be handled on a per-package basis. Packages with "free" manual pages will swap to simply providing them. Packages which require specific generation tools will be evaluated one by one. A list of every generation tool will then be compiled and we can move forwards from there.  In the absolute worst case (where it isn't feasible to package a generation tool), we can provide our own generated manual pages for packages which require them. 

The trickiness comes into play with 3) and dependency resolution. I'm sure the solution will present itself. 
This is marked `future`. Posting here to start the discussion.

**Comment by dylanaraps** [comment]
- [ ] grub (requires `help2man`).

**Comment by aabacchus** [comment]
busybox does have a man page, but it's simply all the `--help` messages for each applet listed. certainly most of the core utilities have dedicated man-pages-posix, and only the ~interesting~ applets (httpd, sendmail, etc) don't have any decent, busybox-specific manuals.

**Comment by dylanaraps** [comment]
OK. Every package without manual pages (or with partial manual pages - ie, pages 
for utilities, none for library)) has been listed above. Now it's just a matter of ticking
each little box.

Notes:

- scdoc has been packaged. This is really nice. Build takes one second and the
   tool clocks in at 80k. I have no qualms about making this a `make` depend.

- gtk-doc looks awful to package (many dependencies, very complex).

- ...

**Comment by dilyn-corner** [comment]
`docbook` is unpleasant in general to deal with packaging-wise, and there was a breaking change in their last major version release; you might have to use an older version for some or all packages requiring `docbook` (for instance, all KDE packages still require `docbook` 4.x afaik; I have no idea about any of these, ofc).

**Comment by jedahan** [comment]
I have docbook-xsl packaged if thats at all helpful https://github.com/jedahan/kiss-repo/tree/main/docbook-xsl . I think it was a prerequisite for docbook-xml, which i am having trouble finding. must be in a repo that went away.

**Comment by aabacchus** [comment]
The `xkeyboard-config` package does not currently provide any documentation, although it exists: https://linux.die.net/man/7/xkeyboard-config.

**Comment by aabacchus** [comment]
Re: docbook, I just came across this utility from the excellent bsd.lv collection: https://mandoc.bsd.lv/docbook2mdoc/
> The docbook2mdoc utility is a converter from DocBook version 4.x and 5.x XML to mdoc. Unlike most DocBook utilities, it's a standalone ISC-licensed ISO C utility with no external dependencies that should compile on any modern UNIX system.
