### ISSUE TITLE
curl Segfault on download completion when /etc/nsswitch.conf contains "hosts: files dns"

### ISSUE THREAD

**Issue by trunc88** [kisslinux/repo#274]
I'm experiencing segfaults the moment kiss (version 5.4.10) finishes downloading the first source file of a package, when /etc/nsswitch.conf contains "hosts: files dns" for dnscrypt-proxy to respect /etc/hosts. This also happens when not using dnscrypt-proxy. No build log is produced, and I'm not sure how to tell what is actually segfaulting, so I don't know what I should do to get debugging info for this. 

`$ kiss b kiss
-> Resolving dependencies
-> Building: explicit: kiss
-> Checking for pre-built dependencies
-> kiss Checking sources
found url+https://github.com/kisslinux/kiss/archive/5.4.10.tar.gz
-> kiss Downloading https://github.com/kisslinux/kiss/archive/5.4.10.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0     12      0  0:00:10  0:00:09  0:00:01    28
Segmentation fault
ERROR kiss Failed to download https://github.com/kisslinux/kiss/archive/5.4.10.tar.gz`

Sorry for not knowing more info to give you, I will gladly provide it if needed.

**Comment by dylanaraps** [comment]
I wonder if #266  fixes this issue.

**Comment by trunc88** [comment]
Oh, curl does segfault outside of kiss with the option set as well. I actually meant to mention that originally but forgot to. I thought it _wasn't_ segfaulting outside of kiss because I guess I never verified it was set when I tested it. Sorry about that.

**Comment by dylanaraps** [comment]
> This also happens when not using dnscrypt-proxy.

So, this occurs even when curl is linked **only** to its default dependencies? 

ie, `libressl`, `zlib`.

**Comment by trunc88** [comment]
I tested again because I realized that I forgot to test the curl flags. It only segfaults with curl -L set. As far as I know curl is only linked to its default dependencies, how should I confirm that?

**Comment by git-bruh** [comment]
@trunc88 The issue seems to be glibc-related since nsswitch.conf is involved, I think it should be opened on gkiss's repo instead, since it isn't a problem on regular KISS.

**Comment by dylanaraps** [comment]
> I tested again because I realized that I forgot to test the curl flags. It only segfaults with curl -L set. As far as I know curl is only linked to its default dependencies, how should I confirm that?

`ldd /usr/bin/curl` or `kiss depends curl` (which just runs `cat "$KISS_ROOT/var/db/kiss/installed/curl/depends"`).

> The issue seems to be glibc-related since nsswitch.conf is involved, I think it should be opened on gkiss's repo instead, since it isn't a problem on regular KISS.

If this is GNU libc related then yeah, the report doesn't belong here.

**Comment by trunc88** [comment]
Ah I'm sorry, totally forgot that this was a glibc thing. I'll go put it on the gkiss repo.

`ldd /usr/bin/curl` gives me `/usr/bin/ldd: error: '/usr/bin/curl' is not a dynamic executable` looks like the build script has `curl_LDFLAGS=-all-static` set
`kiss depends curl` gives me `libressl zlib`. I figured that this probably jus cat'd the installed/depends file. Does this show you what it was actually linked against at build time?

**Comment by dylanaraps** [comment]
> Does this show you what it was actually linked against at build time?

It shows what was manually added to the depends file by the maintainer. If there are any shared libraries/binaries in the package, the package manager will amend the file by adding in any missing dependencies. Seeing as curl is statically linked, this list includes only manually added dependencies.

**Comment by trunc88** [comment]
OK very cool, thank you. Sorry again for posting in the wrong place
