### ISSUE TITLE
[sway/server.c:183] Unable to open wayland socket

### ISSUE THREAD

**Issue by nulln0ne** [kisslinux/repo#280]
I installed sway-tiny, tried to run it and got this error message

**Comment by dylanaraps** [comment]
Send a log (`sway -dV >~/log 2>&1`).

**Comment by nulln0ne** [comment]
> Do you have `XDG_RUNTIME_DIR` set? Is this directory writable by your user?

yes, i set, but it isn't writable by my user. should i give permissions to it?
now i'm going to reinstall kiss and then i will send a log

**Comment by dylanaraps** [comment]
Yes. It must be writable by your user. 

This is documented in the wiki https://kisslinux.xyz/wiki/wayland/install and the post-install hook.
