### ISSUE TITLE
sway-tiny: how to pass arguments to keybindings

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/repo#293]
The mediakeys on sway-tiny and sway-no-seat do work actually. This was a false positive because the mediakeys were already bind and so wev failed to recognize its press. Mediakeys do work!
The real issue however is that no argument is passed to the command executed. E.g `amixer sset Master 5%-` does not work.

**Comment by dylanaraps** [comment]
Is this only in `sway-tiny` or also in `sway-no-seat` and `sway`?

Sounds like https://github.com/DCVIII/sway/commit/bd0ca550682849faa11392564ba1e5313d88405d
which you should try building sway-tiny without.

**Comment by sdsddsd1** [comment]
This happens only in `sway-tiny`.  `sway` and `no-seat` are not affected.

**Comment by dylanaraps** [comment]
Fixed. Thanks
