### ISSUE TITLE
cut new release?

### ISSUE THREAD

**Issue by jedahan** [kisslinux/repo#294]
`kiss update` failed for me with the default 2021.7-6 image, maybe that should be dropped and a new release made with all the improvements to the manager since then?

I can reproduce this issue by running `buildah unshare ./base.sh` from https://github.com/jedahan/kiss-testing/blob/main/base.sh . Should be reproducible in a chroot as well, but I am on a non-linux machine atm.

**Comment by dylanaraps** [comment]
I can reproduce. On it.

**Comment by dylanaraps** [comment]
https://github.com/kisslinux/repo/releases/tag/2021.7-7
