### ISSUE TITLE
efivar: fix build

### ISSUE THREAD

**Issue by git-bruh** [kisslinux/repo#313]
The efivar build fails since it tries to build a test that requires linking to the efivar lib itself, so it fails. The fix is to just disable the test by ':> tests/test-threading'. Log: 
https://termbin.com/2m38

**Comment by dylanaraps** [comment]
Fixed. https://github.com/kisslinux/repo/commit/c29cd78bf35db44b6a16bbb00a8426b906d3eded

**Comment by dylanaraps** [comment]
I cannot reproduce this issue however so let me know if it still occurs. This should do it.

**Comment by dylanaraps** [comment]
This seems to be the actual cause (and fix): https://github.com/rhboot/efivar/pull/169

I'm fine with disabling the test entirely though.
