### ISSUE TITLE
About Xorg and Wayland...

### ISSUE THREAD

**Issue by n1rdeks** [kisslinux/repo#320]
Am I right? U think is Xorg dead? 

K1sslinux suggest only Sway (wlroots). Okay, but how about DWM/Xmonad alternatives? 
River? (https://github.com/ifreund/river/)

DWL in not complete today and he didn't have any depends for later install...

**Comment by dylanaraps** [comment]
> U think is Xorg dead?

Read: https://blogs.gnome.org/uraeus/2019/06/24/on-the-road-to-fedora-workstation-31/

> Once we are done with this we expect X.org to go into hard maintenance mode fairly quickly. The reality is that X.org is basically maintained by us and thus once we stop paying attention to it there is unlikely to be any major new releases coming out and there might even be some bitrot setting in over time. We will keep an eye on it as we will want to ensure X.org stays supportable until the end of the RHEL8 lifecycle at a minimum, but let this be a friendly notice for everyone who rely the work we do maintaining the Linux graphics stack, get onto Wayland, that is where the future is.

It's still early days. There's some years left.

**Comment by n1rdeks** [comment]
thanks.
