### ISSUE TITLE
grim forces -Werror (or clarify instructions when using mold as default linker)

### ISSUE THREAD

**Issue by konimex** [kisslinux/repo#332]
As per https://github.com/wyvertux/wyverkiss/issues/51 and https://libera.irclog.whitequark.org/kisslinux/2021-09-10#30815883, building `grim` with `mold` errors (`-Werror`) because of the `--ld-path` instruction not being used when using Clang (I don't know if this is reproducible in GCC with `-B`). They referred to this instruction:

https://github.com/kisslinux/repo/blob/ba4f3586aa16b9f7cab790b591416998c473850a/extra/mold/README#L48

I think they mistook the *options* as *steps* (as they mentioned using both the alternatives system *and* the `--ld-path` method), so we might need to revisit the number usage there.

**Comment by dylanaraps** [comment]
Rather than disabling `-Werror` (or the unused flag warning) in all affected packages... users can set it themselves if they choose METHOD 2 and are affected by it. Thanks for the issue.
