### ISSUE TITLE
question on perl test failures

### ISSUE THREAD

**Issue by dkwo** [kisslinux/repo#335]
This is more of a question than an issue.

With your config options, do you get any test failure for `perl` 5.34? (make check)
I was packaging it for Void linux, and `x86_64-musl` was failing
```
run/locale.t                                                       (Wstat: 0 Tests: 40 Failed: 2)
  Failed tests:  38-39
../lib/locale.t                                                    (Wstat: 0 Tests: 682 Failed: 1)
  Failed test:  450
```
I wonder whether your config options (or alpine linux patches perhaps) do avoid such failures.

Thanks.

**Comment by dylanaraps** [comment]
Hello, I am yet to have time to look into this. No need to close this.

**Comment by dylanaraps** [comment]
```
Failed 2 tests out of 2525, 99.92% okay.
	../cpan/Socket/t/getaddrinfo.t
	op/magic.t
```

**Comment by dylanaraps** [comment]
Alpine skip the magic test: https://git.alpinelinux.org/aports/tree/main/perl/skip-test-due-to-busybox-ps.patch

**Comment by dkwo** [comment]
Thanks, I was not sure it was appropriate to bother you about this.
I found out that (most of) my test errors go away if I use `Configure` instead of `configure`, as most distros (including KISS) already do.

**Comment by dkwo** [comment]
> Regarding the other failing test see: https://sourceware.org/bugzilla/show_bug.cgi?id=15726

isn't this about glibc though?

**Comment by dylanaraps** [comment]
The musl author is in that thread so I assume musl is also affected.
