### ISSUE TITLE
Why do we need to have [001] Installation section?

### ISSUE THREAD

**Issue by kyx0r** [kisslinux/repo#336]
What's the point of having [001] Installation section if they are all the same?

I mean sure, for a newcomer maybe - but once you know how to install one package
you automatically know how to install any package, just use kiss build <pkgname>.

Ok you may say that there might be some extra steps needed besides kiss build,
but my argument is that there shouldn't ever be extra steps. Afterall that is why we the have
build shell script for every package.

I can userstand the [002] Usage section, but [001] Installation itself is a contradiction
to kiss.

**Comment by dylanaraps** [comment]
The installation section will stay. While the majority of packages use it simply, its purpose is to allow
more complex packages to express any further installation steps. Remember, this README 
convention is adoptable by other repositories and they are also free to omit any sections if the
maintainer deems them unnecessary.

Thanks for the issue.
