### ISSUE TITLE
Clang 13.0.0 errors

### ISSUE THREAD

**Issue by konimex** [kisslinux/repo#343]
So, after LLVM released 13.0.0 and the introduction of several new [compiler flags](https://github.com/llvm/llvm-project/blob/llvmorg-13.0.0/clang/docs/ReleaseNotes.rst#new-compiler-flags) for Clang. We have build failures (because of `-Werror`) in these packages:

- pango (https://termbin.com/4gym)
  We may need to either trim more fribidi-related things, or just use `-Wno-error` on `meson.build`. Unfortunately, `-Wno-unused-but-set-variable` doesn't exist, unlike `-Wno-unused-command-line-argument`.
- sway (https://termbin.com/rtq4)
Fix: see https://github.com/swaywm/sway/commit/ff468584abddcb3f703d407aecf78137fb656472

**Comment by dylanaraps** [comment]
Fixed both, thanks. Note that sway-tiny and sway-no-seat both disable `-Werror` so the patch is not needed there.
