### ISSUE TITLE
Meson 0.60.0 Fails to compile fontconfig

### ISSUE THREAD

**Issue by sn0w3d0wl** [kisslinux/repo#354]
Meson 0.60.0 fails to compile fontconfig but earlier version (Meson 0.59.4 is what I tested) works and successfully compiles fontconfig. I encountered this error when I was installing font-config.

**Comment by konimex** [comment]
This might be a Wyverkiss-specfiic issue (since KISS one still use plain old gmake). Close this one and reopen in Wyverkiss.
