### ISSUE TITLE
`curl` doesn't compile when brotli is available

### ISSUE THREAD

**Issue by Riteo** [kisslinux/repo#361]
For some reason `curl` fails with the following error when brotli is available:
```
/usr/bin/ld: cannot find -lbrotlidec
collect2: error: ld returned 1 exit status
```

Adding `--without-brotli` to the call to `./configure` in `build` solves the problem.

I see you've disabled quite a lot of compression methods too, is it because they face a similar error?
Is this error caused in the first place by the hacky way of compiling it statically implemented in the first few lines of `build`?

**Comment by dylanaraps** [comment]
> I see you've disabled quite a lot of compression methods too, is it because they face a similar error?

Only zstd is disabled? No such error.

>  Is this error caused in the first place by the hacky way of compiling it statically implemented in the first few lines of build?

The "hack" just adds `-all-static` to the linker flags for the curl binary. 
The issue seems to be this: https://github.com/google/brotli/issues/795

**Comment by Riteo** [comment]
> Only zstd is disabled? No such error.

Oh sorry, I thought I had seen more of them.

Regarding the issue I didn't know it was upstream, thanks for investigating!
