### ISSUE TITLE
Firefox 94 from extra repo fails to compile

### ISSUE THREAD

**Issue by Fenix7667** [kisslinux/repo#372]
System:
Intel i5 10400F (x86_64)
RX 550 (AMDGPU Driver, Polaris11)
16GB RAM

Flags:
-j11 -O2 -pipe -march=native

Log:
https://pastebin.com/z8nCN7qY

**Comment by dilyn-corner** [comment]
https://git.alpinelinux.org/aports/commit/community/firefox-esr?id=a408069e75632ce625aea68c70c23ee9e30995a5 Should do it...

**Comment by Fenix7667** [comment]
Tried the patch but I still have the same issue, I am not sure if I applied the patch correctly though. What I did:
1 - Put the patch file inside the patches folder in firefox repo in extra
2 - Generate the checksums for it and change checksums file
3 - Change the sources file to include the patch
4 - Build it

**Comment by Fenix7667** [comment]
Update: I had applied the incorrect patch, the one @dilyn-corner said (https://git.alpinelinux.org/aports/plain/community/firefox-esr/mozwayland-add-missing-stub.patch?id=a408069e75632ce625aea68c70c23ee9e30995a5) should fix this issue correctly.
