### ISSUE TITLE
Pigz v2.6 tarball: unable to fetch

### ISSUE THREAD

**Issue by acid-bong** [kisslinux/repo#374]
**Steps before the problem:** did `kiss u` and then separately `kiss b pigz`, the output is the same.
![pizg 2 6 error](https://user-images.githubusercontent.com/94849097/149780159-8fc010fa-ff55-4ac3-b0b0-121be545091c.png)

**Link check:** error 404. I assume the devs deleted the tarball from their servers

**Comment by acid-bong** [comment]
Ik. Let's consider the message as a proposal

**Comment by acid-bong** [comment]
I mean, letting Dylan know that the repo version is unavailable and needs to be updated in the repo as well, since it replaces the newer version as well

**Comment by F1r3Hydr4nt** [comment]
It would be sweet to get this fixed asap for automation, [broken submodules](https://github.com/gkisslinux/grepo) etc.
