### ISSUE TITLE
xkeyboard-config: source is no longer available

### ISSUE THREAD

**Issue by lealgo** [kisslinux/repo#376]
trying to install sway I get:

"ERROR xkeyboard-config Failed to download https://alpine.global.ssl.fastly.net/alpine/edge/main/x86_64/libx11-1.7.2-r0.apk"

**Comment by lawrencelogoh** [comment]
You can change the version number in the sources for xkeyboard-config. Check https://alpine.global.ssl.fastly.net/alpine/edge/main/x86_64/
