### ISSUE TITLE
Kernel Binary

### ISSUE THREAD

**Issue by al1r4d** [kisslinux/repo#385]
Is there a Linux kernel bin? I'm too lazy to compile a kernel because I use an Intel Atom, which is the slowest CPU series.

**Comment by aabacchus** [comment]
You probably could get one from another distribution, but configuring and tweaking the kernel is one of the most rewarding parts of setting up the system. Start with a `make localyesconfig` and add stuff you want, take away stuff you don't need. Yes, it will take ages to compile (don't forget `make -jN`).
