### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by rajncnc** [kisslinux/repo#395]
echo trusted-key 0x13295DAC2CF13B5C >>/root/.gnupg/gpg.conf
for /root/ .gnupg/gpg.conf
it reports permission denied.

prior to that kiss build gnupg1 did not work.

**Comment by aabacchus** [comment]
If you couldn't build `gnupg1`, the directory `/root/.gnupg/` probably doesn't exist. Are you running as root or a normal user (what is the output of `id -nu`)?

What didn't work about building gnupg1? If the build failed, it will have created a log file (something like `Log stored to /root/.cache/kiss/logs/....`). Can you upload the contents of that file to a pastebin or to here?

By the way, the KISS community is maintaining a set of repos which are updated over at https://codeberg.org/kiss-community, so you may wish to change your repos to use those over there.

**Comment by umop3plsdn** [comment]
i'm glad i saw this issue before I installed. Is there a reason this isn't reflected in the install instructions on the website? I would have never even known lolol
