### ISSUE TITLE
Boot loop issue with legacy BIOS on GRUB 2.06.  Must compile with -Os flag

### ISSUE THREAD

**Issue by ghost** [kisslinux/repo#396]
As the project is inactive, I am just leaving this tip here for anyone who it may help in the future.

There is an issue with GRUB 2.06, which is the version supplied by KISS.  If you are using legacy BIOS instead of UEFI, you must compile GRUB with `-Os` instead of `-O2` 

Some discussion about the issue can be found [here](https://www.linuxquestions.org/questions/slackware-14/legacy-boot-bug-with-grub-2-06-boot-loop-stuck-at-grub-loading-current-4175696226/)

**Comment by rilysh** [comment]
Whenever such issues occurs, it's most likely that either the software or the compiler has bugs.
