### ISSUE TITLE
Create a games repository

### ISSUE THREAD

**Issue by naltun** [kisslinux/repo#42]
Lots of Linux users love games; I think it is inevitable then that we will include game packages.

My question: do we put these packages in public, or do we create a games repository?

If you guys decide to create a games repo, then I believe it would be best to create the directory for the first games-related PR.

**Comment by dylanaraps** [comment]
This is very out of scope for KISS. I'm not even sure if I want games in `public` (*I need to think about it*). KISS is setup so you can easily create your own repositories to package whatever you like. My intention is for the base repositories to be small and to only contain everything needed for a "usable" system (xorg-server, web browser and media player).

**Comment by naltun** [comment]
> This is very out of scope for KISS. I'm not even sure if I want games in `public`... KISS is setup so you can easily create your own repositories to package whatever you like.

I did read this. And this makes sense. I even like it.

Think about it, but I think it's definitely okay then not to have this as a feature of KISS.

**Comment by dylanaraps** [comment]
Closing this as I've decided not to include a Games repository.
