### ISSUE TITLE
[Tracker] ffmpeg

### ISSUE THREAD

**Issue by konimex** [kisslinux/repo#43]
If anyone has any recommendations on what to enable/disable, please reply here.

- [x] alsa-lib
- [x] libass
- [x] libdrm
- [x] lame
- [ ] openh264
- [x] opus
- [x] libvorbis
- [x] libtheora
- [x] libogg
- [x] libwebp
- [x] wavpack
- [x] x264
- [x] x265
- [x] xvid
- [ ] speex
- [x] libvpx
- [ ] libaom

**Comment by neoraindaemon** [comment]
I'm gonna recommend x264.

**Comment by konimex** [comment]
Whoops, closed by accident. My bad.

**Comment by dylanaraps** [comment]
Do we need `openh264` if we have `x264`? They seem to do the same thing.

**Comment by dylanaraps** [comment]
Do we also need `speex`? I've packaged everything else.

**Comment by neoraindaemon** [comment]
There's no threading in openh264. ffmpeg has a native decoder. I just generally associate x264 with .mkv files. Speex for the visually-impaired, perhaps. Sidenote: are you able to build bspwm without checksum errors?

**Comment by dylanaraps** [comment]
> are you able to build bspwm without checksum errors?

I don’t personally use it so I haven’t built it. I’ll try when I am home
later.
