### ISSUE TITLE
New package: apache2

### ISSUE THREAD

**Issue by naltun** [kisslinux/repo#47]
I'm already making progress on it [here](https://github.com/naltun/repo/tree/add-httpd).

Supporting packages:
* apr
* apr-util
* PCRE

To be continued...

**Comment by naltun** [comment]
Currently, I am getting this error:
![image](https://user-images.githubusercontent.com/7507990/61974573-d8ee9800-afb4-11e9-9957-a59cd61da2b5.png)

**Comment by naltun** [comment]
> dylan
> Apr + Apr-util can be bundled with Apache.

> \> Make sure you have APR and APR-Util already installed on your system. If you don't, or
> \> prefer to  not use the system-provided versions, download the latest versions of both APR
> \> and APR-> Util  from Apache APR, unpack them into /httpd_source_tree_root/srclib/apr and 
> \> /httpd_source_tree_root/srclib/apr-util (be sure the directory names do not have version 
> \> numbers; for example, the APR distribution must be under
> \> /httpd_source_tree_root/srclib/apr/) and use ./configure's --with-included-apr option.

> This makes more sense as I doubt any other packages will depend on these two libraries.

**Comment by dylanaraps** [comment]
Re-open this in https://github.com/kisslinux/community
