### ISSUE TITLE
Propose: initramfs/initrd support

### ISSUE THREAD

**Issue by whoizit** [kisslinux/repo#57]
Seems like initramfs required to boot from encrypted /boot

https://cryptsetup-team.pages.debian.net/cryptsetup/encrypted-boot.html
https://wiki.gentoo.org/wiki/Custom_Initramfs
https://wiki.voidlinux.org/Full_Disk_Encryption_w/Encrypted_Boot

Seems like grub-mkimage can build initramfs archives https://manpages.debian.org/buster/grub-common/grub-mkimage.1.en.html

**Comment by dylanaraps** [comment]
Options:

- [dracut](https://github.com/dracutdevs/dracut)
- [mkinitfs](https://github.com/alpinelinux/mkinitfs)
- [mkinitcpio](https://github.com/falconindy/mkinitcpio)
- [update-initramfs](https://gitlab.com/keks24/update-initramfs)
- Our own(?)

**Comment by dylanaraps** [comment]
OK. I have come to the conclusion that we need our own tool. I will be writing it, however it will only support loading required modules to begin with. The sole purpose for the time being is to allow users to actually boot. 

Things like encryption will come later through contributions by the willing.

**Comment by whoizit** [comment]
NIH?

**Comment by dylanaraps** [comment]
No.

These above tools are either deprecated, don't run on `musl`, are heavily locked into their parent distributions or require many additional dependencies. I'll also mention the fact that these are all written in terrible and unsafe shell. There's also the matter of most of these being written in `bash`.

This isn't a matter of NIH, it's a matter of finding a suitable tool. None of the above listed are suitable. We are striving for simplicity here, should we not and just settle for something that works "OK"?

**Comment by dylanaraps** [comment]
Work is being done here: https://github.com/kisslinux/kiss-initramfs

**Comment by whoizit** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/Documentation/device-mapper/dm-init.txt?id=6bbc923dfcf57d6b97388819a7393835664c7a8e

**Comment by whoizit** [comment]
I'm not understand how it works, should I use grub with luks module or should i use separate boot or what. Can somebody explain it to me?

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/device-mapper/dm-init.rst

**Comment by dylanaraps** [comment]
The initramfs-tool is not yet functional and encryption support will come later.

**Comment by whoizit** [comment]
I understand, but I'm talking about a mechanism that was added to the 5.1 kernel, which allows you to do without initramfs when encrypting the root

**Comment by dylanaraps** [comment]
Closing as full drive encryption is supported without an `initramfs` since Linux 5.1.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/device-mapper/dm-init.rst

**Comment by illiliti** [comment]
seems CONFIG_DM_INIT not supporting detached header+key or im wrong?Anyway i can't understand how to boot enc root only with kernel

**Comment by dylanaraps** [comment]
I'm sorry but I can't really help you here. I don't encrypt my drives (*nor have I ever*) so I'm not knowledgeable in this area. I'm hoping someone else can chime in as from what I've read (*and can understand*), `CONFIG_DM_INIT` should work for this use-case.

**Comment by illiliti** [comment]
So.. Hello again :) .  I decided to write my own initramfs,because i want easy configuration, not like dracut or mkinitcpio which are very very complicated. Progress goes here - https://github.com/illiliti/initramfs . Currently i'm working hard to implement basic features like drivers loading and binaries installing...etc. Any help will be appreciated! Don't be evil, it's my first project.

**Comment by imxade** [comment]
can [initramfs-tools](https://salsa.debian.org/kernel-team/initramfs-tools) be an option? 

Currently, used by [chimera linux](chimera.org) with musl
https://github.com/chimera-linux/cports/tree/master/main/initramfs-tools

**Comment by illiliti** [comment]
there's no lock-in. you're free to use whatever you want.

**Comment by imxade** [comment]
> there's no lock-in. you're free to use whatever you want.

Wanted to know if it could be officialy supported. 
Currently, I generate initramfs from other distro

**Comment by illiliti** [comment]
what kind of support do you need? kisslinux doesn't officially support initramfs. it is explicitly stated on the website. you're on your own in this regard.

**Comment by imxade** [comment]
> what kind of support do you need? kisslinux doesn't officially support initramfs. it is explicitly stated on the website. you're on your own in this regard.

yes, i know. But wasn't dylan searching for a suitable tool (he probably also wanted to support it officially)
So, I suggested a mature one :)

**Comment by illiliti** [comment]
No, he wasn't

**Comment by imxade** [comment]
> seems CONFIG_DM_INIT not supporting detached header+key or im wrong?Anyway i can't understand how to boot enc root only with kernel

I know it's late but didn't saw that earlier, the process is pretty straight forward
here's a guide on how to use **dm-mod.create** https://forums.gentoo.org/viewtopic-t-1110764-start-0.html

In my case I use grub to trigger the encrypted kernel so I don't need a USB stick

**Comment by imxade** [comment]
1. right, but y would you allow someone to access your system & /proc/cmdline. Doesn't that defy the point of encryption.
2. it does work with luks1, should also work with luks2 (but haven't tried yet as grub doesn't fully support luks2)
3. no idea, couldn't get TPM2 to unlock anything on qemu.

(github doesn't notify about anything. So, I won't always be able to reply)
