### ISSUE TITLE
0.0.20-musl kiss-chroot.tar.xz invalid repo file permissions

### ISSUE THREAD

**Issue by sebastianertz** [kisslinux/repo#62]
```
diff --git a/.travis.yml b/.travis.yml
old mode 100644
new mode 100755
diff --git a/LICENSE.md b/LICENSE.md
old mode 100644
new mode 100755
diff --git a/README.md b/README.md
old mode 100644
new mode 100755
diff --git a/core/autoconf/checksums b/core/autoconf/checksums
old mode 100644
new mode 100755
diff --git a/core/autoconf/depends b/core/autoconf/depends
old mode 100644
new mode 100755
diff --git a/core/autoconf/sources b/core/autoconf/sources
old mode 100644
new mode 100755
diff --git a/core/autoconf/version b/core/autoconf/version
old mode 100644
new mode 100755
diff --git a/core/automake/checksums b/core/automake/checksums
old mode 100644
new mode 100755
diff --git a/core/automake/depends b/core/automake/depends
old mode 100644
new mode 100755
diff --git a/core/automake/sources b/core/automake/sources
```
and so on

**Comment by dylanaraps** [comment]
My bad.

I will fix this in a new `chroot` release tomorrow.

**Comment by dylanaraps** [comment]
The reason for these permissions is to allow any user to do a `git pull` of the repository (this happens in `kiss update`). The other solution is to use `sudo` during the `git pull` in the package manager.

Thoughts?

**Comment by dylanaraps** [comment]
I'm in the process of creating a new `chroot` to fix this issue. `kiss update` will now call `sudo` if permissions are required to update the system-wide repository. :+1:

**Comment by dylanaraps** [comment]
Fixed.

https://github.com/kisslinux/repo/releases/tag/0.0.21-musl

This also fixes:

- `man` now works.
- `update-ca-certificates --fresh` now works.
- All packages updated.

**Comment by sebastianertz** [comment]
Thanks, kisslinux is so great.
