### ISSUE TITLE
Issue building glib

### ISSUE THREAD

**Issue by swinny89** [kisslinux/repo#77]
building glib fails. The below is what looks to be the relevant portion of the build output. Let me know if you need more info.

```
rm: '/var/cache/kiss/pkg-6459/glib/usr/share/gettext' is a directory
!> [glib]: Build failed.
```

**Comment by dylanaraps** [comment]
Fixed. https://github.com/kisslinux/repo/commit/fbb0edb078cd80736dc170c55af4511c42ed6b80

**Comment by dylanaraps** [comment]
Run `kiss update` and rebuild `glib`. :+1:

**Comment by swinny89** [comment]
@dylanaraps 
It works!
