### ISSUE TITLE
Propose: Potential fork to continue `vdev` development.

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#78]
`vdev` is a minimal `udev` replacement which also includes its own version of `libudev` (*for compatability with `libinput` and other software which depends on `udev`*). Sadly development stopped a few years ago and it is now too out of date with `libudev` to be of any use.

I propose we **attempt** to revive development through a direct fork of the project. From what I understand, the `libudev` compatibility library is just `udev`'s with changes to work with any device manager available!

This isn't a set in stone idea. I'd like to first figure out just **how** much work is required and what exactly needs fixing. It's an interesting idea nonetheless.

**NOTE:** Splitting `vdev` into `libudev`/`vdev` allows for `libudev` to be used with `mdev`, `vdev`, `smdev` etc etc while still allowing for a working `libinput` etc.

More information:

> Vdev comes with a reference configuration and set of helper programs that make it usable out-of-the-box, with no subsequent tweaking required. The Linux port is a drop-in replacement for udev: it generates an equivalent /dev tree, as well as an equivalent /run/udev tree. It also ships with a "libudev-compat" library that is ABI-compatible with libudev 219. Libudev-linked software such as the X.org X server can use vdev and libudev-compat without recompilation. In addition, the Linux port interoperates with but does not depend on the devtmpfs filesystem.

Link: https://github.com/jcnelson/vdev

**Comment by dylanaraps** [comment]
- `vdev`'s `libudev` is at `219` and `udev`'s `libudev` is at `228`.

**Comment by dylanaraps** [comment]
This won't be possible sadly.

**Comment by illiliti** [comment]
https://github.com/illiliti/libudev-zero
