### ISSUE TITLE
issue building cmake

### ISSUE THREAD

**Issue by swinny89** [kisslinux/repo#79]
getting this:

```
/var/db/kiss/repo/extra/cmake/build: line 10: can't open /var/db/kiss/repo/extra/cmake/build/version: no such file
!> [cmake]: Build failed.

```
I'm guessing it should be `/var/db/kiss/repo/extra/cmake/version` instead of `/var/db/kiss/repo/extra/cmake/build/version`

below is the relevant line in the build script, but I don't know bash enough to know what I am looking at.

```
IFS=. read -r ver1 ver2 _ < "${0%*/}/version"
```

**Comment by dylanaraps** [comment]
Fixed. https://github.com/kisslinux/repo/commit/117e81823be5a8d0f3556355f79218e9aa460498
