### ISSUE TITLE
[Question] Why use of dhcpcd over sdhcp

### ISSUE THREAD

**Issue by xythz** [kisslinux/repo#87]
It seems like sdhcp would be better aligned with the philosophy of KISS Linux so im posting this to see why dhcpcd was choosen.

**Comment by dylanaraps** [comment]
- `sdhcp` has no support for IPv6 (See [TODO](http://git.2f30.org/sdhcp/file/TODO.html)).
- Busybox also comes with `udhpcd` however it requires a rather [messy shell-script](https://git.busybox.net/busybox/tree/examples/udhcp/simple.script) to function.

NOTE: `udhpcd` is installed by default if you want to use it. `dhcpcd` is **not** installed by default and you can package `sdhcp` for yourself if you like.
