### ISSUE TITLE
libaio fails to build

### ISSUE THREAD

**Issue by whoizit** [kisslinux/repo#89]
http://sourceware.org/dm/

`kiss build lvm2`
![2019-09-03_06-29](https://user-images.githubusercontent.com/359276/64142376-59a27e80-ce14-11e9-9419-398fb625e553.png)

**Comment by whoizit** [comment]
hm... seems like lvm2 not compile directry (like kiss b lvm2), but compile if I do kiss b cryptsetup)
device-mapper parts (`dmsetup`)I have now, but idk which package owns them.

**Comment by dylanaraps** [comment]
I can't reproduce this at all. That `make` error is from `libaio` and it has always built fine for me. What are the exact commands you ran?

**Comment by whoizit** [comment]
`kiss build lvm2` i guess

**Comment by dylanaraps** [comment]
Can you reproduce the error with `kiss build libaio`?

**Comment by whoizit** [comment]
no, I can't
