### ISSUE TITLE
libressl build has side effect of deleting all man pages?

### ISSUE THREAD

**Issue by jedahan** [kisslinux/repo#90]
https://github.com/kisslinux/repo/blob/23640d4e2658c1c4171dc0c1850e56ae9c218c17/core/libressl/build#L15

Is this intentional? Am I reading the script wrong? Is there a good reason to do this?

**Comment by dylanaraps** [comment]
This deletes 3500~ (iirc, it's a lot either way) man pages which are of no use to the end user. If you'd like to keep them you can create a user repository and maintain your own `libressl` package. We are also working on a `USE_FLAGS` type of system for the future.

**Comment by jedahan** [comment]
It just seems weird to be part of libressl - would you be open to a PR where I created a 'remove-man' package that was part of the default install that did this explicitly? Or just to wait for a `FLAGS` system?

**Comment by dylanaraps** [comment]
Wait for the `FLAGS` system.
