### ISSUE TITLE
xorg-server requirement for xf86-video-amdgpu

### ISSUE THREAD

**Issue by lieuxnoir** [kisslinux/repo#92]
#### ***Required***
Xorg-Server-1.20.5 (must be built with glamor enabled)

Source: http://www.linuxfromscratch.org/blfs/view/svn/x/x7driver.html#xorg-amdgpu-driver

**Comment by dylanaraps** [comment]
Working on this now. :+1:

**Comment by dylanaraps** [comment]
Done. :+1:
