### ISSUE TITLE
Rust package checksum mismatch

### ISSUE THREAD

**Issue by nikotidar** [kisslinux/repo#96]
![rust-mismatch](https://user-images.githubusercontent.com/49534825/65384920-64389f80-dd52-11e9-849f-b4fb35ecfd09.png)

**Comment by dylanaraps** [comment]
Should be fixed in: https://github.com/kisslinux/repo/commit/3e59edafee6118c7387ae47f8accde203c3f2d13

**Comment by nikotidar** [comment]
I fix this issue by regenerate checksum
