### ISSUE TITLE
Xorg is not compatible with the goal of simplicity

### ISSUE THREAD

**Issue by ddevault** [kisslinux/repo#99]
Wayland is a much, much simpler design. The idea that X11 is simpler or better than Wayland is not based in fact, but cargo culting.

**Comment by dylanaraps** [comment]
With the present situation, even if KISS provided Wayland it'd still need to provide Xorg (*specifically `xwayland`*) and this is arguably *less* simple than just providing Xorg. 

Simplicity doesn't have a single definition and my decisions are based on more than simplicity of design or lines of code. 

I don't think Wayland is quite ready nor do I see it as a viable alternative right now. I don't know what the future holds but until (*and if*) things improve only Xorg will be packaged by default. 

I think it's unfair to claim that `software_name` software is incompatible with KISS' goals. I've spent time evaluating the alternatives and came to the conclusion that what we provide (*in the official repositories*) is the "right" choice.

Of course you may disagree with this and the beauty of KISS is that you can create your own repository and package the software you desire. Repositories created by users can be shared between users and are functionally no different to the official ones.

Hell, Xorg isn't even installed by default. It's just the officially supported option.
